### ISSUE TITLE
'to_pandas' hangs when running as part of a systemd service

### ISSUE THREAD

**Issue by ahussey-redhat** [nfstream/nfstream#102]
**Describe the bug**
I have a basic python application which uses nfstream's NFStreamer to categorise flows from PCAPs. Running the application as part of a virtualenv works perfectly and outputs correctly. When run as a systemd service, everything runs correctly up until the point that I convert the NFStreamer object/result `to_pandas`. I get no response and the program just seems to halt.

**To Reproduce**
1. Create a basic python application where you use `NFStreamer` to parse a PCAP file
    1. Have a function that does something similar to the following:
  ```python
  nf_streamer = NFStreamer(
    source=<pcap_file>
  )
  print('parsed')
  nf_streamer.to_pandas()[["src_ip","dst_ip","protocol","application_name"]]
  print('converted')
  ``` 
2. Create a systemd  service unit that uses a virtualenv to run the application
    1. Something like:
  ```bash
  [Unit]
  Description=Stream categorizer
  
 [Service]
 Type=simple
 ExecStart=/home/user/virtualenv/bin/python3 
  /home/user/virtualenv/bin/stream_categorizer
  ```
3. Reload service files `systemctl daemon-reload`, start the service `systemctl start stream_categorizer` and follow the output `journalctl -fu stream_categorizer`. Get it to process a PCAP, and you should see the output `parsed` but never see `converted`. The program will also no longer process any new PCAPs
  The PCAP will be processed but will hang when converting to pandas.
  
**Expected behavior**
PCAP is processed and results are converted to a pandas dataframe.

**Screenshots**
~~N/A~~

**Desktop (please complete the following information):**
 - OS: RHEL8
 - Python version 3.6.8
 - NFStream version 6.3.5

**Additional context**
I've trunkated the python function and systemd service file a lot, but there should be enough information there to replicate the issue in a simple way

**Comment by aouinizied** [comment]
HI @ahussey-redhat,

Can you please retry with to_csv method in order to see if the problem comes from pandas itself or from a more specific scenario?

Zied

**Comment by ahussey-redhat** [comment]
Sorry about my delayed response. Happy to keep this issue closed.
For what we were trying to do nfstreamer might not have been the ideal candidate, we ended up using tshark, as we were just wanting to categorize protocols
