### ISSUE TITLE
Wheel for Alpine linux

### ISSUE THREAD

**Issue by adamjanovsky** [nfstream/nfstream#103]
Since many CI/CD pipelines are utilizing Alpine linux, it would be handy to have built wheel package available for the platform. Listing available wheels on `python:3.8-alpine` docker image yields

```
/ # pip index versions nfstream
nfstream (3.1.0)
Available versions: 3.1.0, 1.0.3, 1.0.2, 1.0.1, 1.0.0, 0.5.0, 0.4.0, 0.3.1, 0.3.0, 0.2.0, 0.1.0
```

It would be nice to reintroduce Alpine as a target for your PyPi distributions. Do you consider compiling new versions also for Alpine somewhen in near future?

**Comment by aouinizied** [comment]
@adamjanovsky it would be great but not yet planned. I will let this issue open and will come back to you as soon as there is plans to extend the CI platforms.
Do you have any link to a project using github actions CI/CD and running on alpine?

Zied

**Comment by adamjanovsky** [comment]
> @adamjanovsky it would be great but not yet planned. I will let this issue open and will come back to you as soon as there is plans to extend the CI platforms. Do you have any link to a project using github actions CI/CD and running on alpine?
> 
> Zied

That'd be great. I've figured that I miss this feature in one of mine projects as well. So I guess I can try to prepare it and provide some guidance subsequently. I'll report if and when I succeed.

**Comment by aouinizied** [comment]
@adamjanovsky starting from version 6.5.2, wheels are published for Alpine Linux: https://pypi.org/project/nfstream/6.5.2/#files
