### ISSUE TITLE
Application detection

### ISSUE THREAD

**Issue by Nirikshatk** [nfstream/nfstream#105]
Hi, 
I am new to networking and nfstream.
 I am trying to detect applications installed on the computer (Passively) by using the network traffic, i see in nfstream we has an output field for application_name.I tried running it, But i see that in application name i am getting is
 the protocol names like, application_name=TLS, application_name=TLS.AmazonAWS, application_name=DNS. 
As per my understanding these (DNS,HTTP,TLS, etc)  are protocols. 
Is there a way to get application names like, visual studio, brave browser, adobe reader, gns3 , google chrome, anydesk etc.

I am getting only Mozilla Firefox application name in user_agent field :
NFlow(id=110,
      expiration_id=0,
      src_ip=10.180.7.188,
      src_mac=bc:e9:2f:a5:a8:d6,
      src_oui=bc:e9:2f,
      src_port=41948,
      dst_ip=180.149.59.136,
      dst_mac=00:04:96:82:70:ee,
      dst_oui=00:04:96,
      dst_port=80,
      protocol=6,
      ip_version=4,
      vlan_id=0,
      tunnel_id=0,
      bidirectional_first_seen_ms=1645703427413,
      bidirectional_last_seen_ms=1645703509177,
      bidirectional_duration_ms=81764,
      bidirectional_packets=23,
      bidirectional_bytes=2844,
      src2dst_first_seen_ms=1645703427413,
      src2dst_last_seen_ms=1645703509138,
      src2dst_duration_ms=81725,
      src2dst_packets=12,
      src2dst_bytes=1221,
      dst2src_first_seen_ms=1645703427452,
      dst2src_last_seen_ms=1645703509177,
      dst2src_duration_ms=81725,
      dst2src_packets=11,
      dst2src_bytes=1623,
      splt_direction=[0, 1, 0, 0, 1, 1, 0, 0, 1, 0],
      splt_ps=[74, 74, 66, 487, 66, 955, 66, 66, 66, 66],
      splt_piat_ms=[0, 39, 0, 0, 39, 2, 0, 10001, 39, 10165],
      application_name=HTTP.OCSP,
      application_category_name=Network,
      application_is_guessed=0,
      requested_server_name=r3.o.lencr.org,
      client_fingerprint=,
      server_fingerprint=,
      **user_agent=Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:97.0) Gecko/20100101 Firefox/97.0,
      content_type=application/ocsp-response)**

Please guide me as soon as possible regarding this.

**Comment by aouinizied** [comment]
Yes, if you are running nfstream on the host that is generating the traffic then, you can enable what you want to get by setting system_visibility_mode to 1 system_visibility_poll_ms=0 as example.

Zied
