### ISSUE TITLE
nfstream can't handle raw packet data?

### ISSUE THREAD

**Issue by lifanxin** [nfstream/nfstream#114]
When use nfstream to handle pcap files with raw packet data, it return nothing.
Maybe these formats have not been considered, how should I deal with it?

the raw packet data like this
![1](https://user-images.githubusercontent.com/26763226/158015267-911c903f-812e-4990-95bc-fcb1252292d3.png)

**Comment by lifanxin** [comment]
the raw packet data means don't have the ethernet layer

**Comment by lifanxin** [comment]
Ok, I got it. It just like issue #104 . linux will be fine, but windows will be return nothing. This is a confusing questiion.

**Comment by aouinizied** [comment]
Thanks for reporting this issue. Indeed it was related to how raw datalink type was handled on Windows. 
This is fixed by https://github.com/nfstream/nfstream/commit/00449108bd3b2726f5507bb37e036691fd6d7253 and this patch will be part on next the release.

**Comment by lifanxin** [comment]
Thanks for your contribution, honestly, it's an amazing project.
