### ISSUE TITLE
FlowBytes/s, FlowPackets/s & other features

### ISSUE THREAD

**Issue by foongminwong** [nfstream/nfstream#118]
Hi,
I was looking at the [list of features](https://www.nfstream.org/docs/api#nflow-core-features) in nfstream and they are quite comprehensive & detailed. 

Quick question, does nfstream have similar features like `FlowBytes/s`, `FlowPackets/s`, `Active Mean`, `Idle Mean`, etc. in [CICFlowMeter](https://github.com/ahlashkari/CICFlowMeter/blob/master/ReadMe.txt)?

Thank you!

Notes: 

- I can somehow generate `FlowPackets/s`  = (` bidirectional_packets` / `bidirectional_duration_ms`) in nfstream. 

- When calculating the `FlowBytes/s` using (`bidirectional_bytes`/`bidirectional_duration_ms`) in nfstream, the values are somehow different from what CICFlowMeter generated.  Is it because the `bidirectional_bytes` generated will depend on different accounting_mode?

- Trying to figure out how to calculate `Active Mean` & `Idle Mean` using existing nfstream features...

**Comment by aouinizied** [comment]
@foongminwong Can you provide a pcap file and the expected output in order to be able to help you?

Best regards,
Zied

**Comment by foongminwong** [comment]
Hello @aouinizied , thank you for your reply! Just recently found out that the current list of NFStream statistical features is sufficient enough for now, thus getting similar `Active Mean` & `Idle Mean` in CICFlowMeter won't be useful. This can be closed :)

**Comment by aouinizied** [comment]
@foongminwong Thaks for the feedback,  do not hesitate to upgrade to lastest version as you will have important speed gain.

Regards,
Zied

**Comment by souravs17031999** [comment]
@foongminwong were you able to extract all the features same as CICflowmeter ?

**Comment by drnpkr** [comment]
> @foongminwong were you able to extract all the features same as CICflowmeter ?

You won't be able to get the same feature set. 

Be aware that there are some problems with CICFlowMeter and the datasets it generates: https://hal.science/hal-03775466

**Comment by souravs17031999** [comment]
@drnpkr thanks for that info.
Actually, I am working on intrusion detection and could only find CICIDS2017 (or 2018, 2019) datasets which as it claims "resembles real world traffic".

Do you know anything better that can help me in this direction ?

**Comment by drnpkr** [comment]
I provided the link above. The Authors remeasured the dataset while fixing the errors. There is a link to the repo in the paper.
