### ISSUE TITLE
Support for list of consecutive capture files as source

### ISSUE THREAD

**Issue by Schwaggot** [nfstream/nfstream#121]
Hello, I was wondering if it would be possible to add support for a list of consecutive files as input, i.e., sliced Pcap captures. Due to RAM or disk space requirements it might not be always possible to merge all files into one big capture upfront. I know that some publicly available data sets partition their captures in slices of 2gb for example. As a start the NFStreamer could take a list of files that are sorted by time, meaning it would just have to start analyzing the first file in the list and once finished reading it continue to the next until all files are read. As flows may continue across file borders this would not be the same as running the NFStreamer for each file individually, it would need to keep its state and continue with the next file instead.

Thanks!

**Comment by aouinizied** [comment]
@Schwaggot are you interested with contributing with a PR regarding this feature? This would be awesome!

Zied

**Comment by Schwaggot** [comment]
Yeah, I'll have a look into it.

**Comment by stefanDeveloper** [comment]
I'd also interested in this feature

**Comment by Schwaggot** [comment]
@aouinizied You were right, a fresh checkout and update to current master branch appears to have fixed the build issue. I have created a PR for this topic here: https://github.com/nfstream/nfstream/pull/131
