### ISSUE TITLE
Can't install nfstream from source "undefined symbol: ibv_create_cq"

### ISSUE THREAD

**Issue by sooualil** [nfstream/nfstream#126]
**Describe the bug**
I wanted to fork the repository to test some tweaks, but I seemed to have a problem installing my fork, turned out there's some compiling issue after installing nfstream even from the original source repository which gives an error when importing nfstream:
`ImportError: /.../python3.6/site-packages/_lib_engine.abi3.so: undefined symbol: ibv_create_cq`

**To Reproduce**
1. Follow the exact installation steps in [the docs](https://www.nfstream.org/docs/#installation-guide)

**Expected behavior**
Nfstream installed/working without fatal errors

**Screenshots**
Not screenshots but a [file](https://github.com/nfstream/nfstream/files/8775934/output.txt) containing the commands I ran and their outputs

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Python version 3.6
 - NFStream version 6.5.2

**Additional context**
Nfstream works fine with `pip install nfstream`
Tried on 3 different machines without luck

**Comment by aouinizied** [comment]
@sooualil Thanks for reporting. 
This is due to libpcap configuration. Adding `-disable-rdma` at the end of this [line](https://github.com/nfstream/nfstream/blob/1322d6b1e40a8a242e6f5df4b51d8c39a8db999d/nfstream/engine/scripts/build_linux.sh#L21) should fix your issue. 

Zied

**Comment by Schwaggot** [comment]
@aouinizied I have the very same problem. I forked the repo to work in the multiple file sources PR and now I am stuck while building from source. The line you referenced for `build_linux.sh` now looks as follows:
```
./configure --enable-ipv6 --disable-universal --enable-dbus=no --without-libnl --disable-rdma
```
But still after running `python3 prepare.py` and `python3 -m pip install .` I get the same error:
```
Traceback (most recent call last):
  File "/home/schwaggot/Development/nfstream/examples/multiple_file_sources.py", line 16, in <module>
    from nfstream import NFStreamer
  File "/home/schwaggot/Development/nfstream/nfstream/__init__.py", line 17, in <module>
    from .streamer import NFStreamer
  File "/home/schwaggot/Development/nfstream/nfstream/streamer.py", line 26, in <module>
    from .meter import meter_workflow
  File "/home/schwaggot/Development/nfstream/nfstream/meter.py", line 16, in <module>
    from .engine import create_engine, setup_capture, setup_dissector, activate_capture
  File "/home/schwaggot/Development/nfstream/nfstream/engine/__init__.py", line 16, in <module>
    from .engine import create_engine, setup_capture, setup_dissector, activate_capture
  File "/home/schwaggot/Development/nfstream/nfstream/engine/engine.py", line 16, in <module>
    from _lib_engine import ffi, lib
ImportError: /home/schwaggot/Development/nfstream/venv/lib/python3.9/site-packages/_lib_engine.abi3.so: undefined symbol: ibv_create_cq

Process finished with exit code 1
```
