### ISSUE TITLE
Running nfstream6.5.1 program on windows gets stuck for a long time

### ISSUE THREAD

**Issue by 199661** [nfstream/nfstream#127]
**Describe the bug**
I installed nfstream6.5.1 using pip, but only a few thousand pieces of data are output when performing large file (200M) traffic feature extraction on windows11. Also, I changed the pcap file and the version of nfstream to no avail. The program will get stuck in the Nfstreamer stage.
**To Reproduce**
1. There is no problem under linux, but when I install it according to the normal steps on my window 11 and use the official sample code, it will get stuck.

**Expected behavior**
How does nfstream work normally under windows11

**Desktop (please complete the following information):**
 - OS:windows11
 - Python version:3.7
 - NFStream version:6.5.1 & 6.5.0

**Additional context**
No additional information，thanks

**Comment by aouinizied** [comment]
@199661 Can you please fix the version to 6.5.1 and provide a sample pcap where we can reproduce the issue?

**Comment by aouinizied** [comment]
@199661 any updates?

**Comment by NLZer0** [comment]
Have a same problem with cic-ids2017 (https://www.unb.ca/cic/datasets/ids-2017.html)
NFStream version 6.5.1, Python 3.9,7

**Comment by aouinizied** [comment]
@NLZer0 @199661 Thanks for the reporting this issue. We were able to reproduce it and to fix it. The patch will be part of the next release.
