### ISSUE TITLE
How does nfstream handle a large number of small files？

### ISSUE THREAD

**Issue by SunEternal** [nfstream/nfstream#128]
I've observed that NFStream is quick with large files, but slow with multiple small files. Are there any good ways to solve this problem.

**Comment by aouinizied** [comment]
@SunEternal Can you provide us with more details? What do you mean by slow? Do you have some metrics?

Zied

**Comment by SunEternal** [comment]
I have observed that when working with a large PCAP file, he usually solves it quickly in a matter of seconds. However, when processing smaller PCAP files, it also takes about 2 seconds. I have hundreds of thousands of small PCAP files and it's hard to deal with them. I tried to look at the source code, but didn't think of anything to solve it.

**Comment by drnpkr** [comment]
@SunEternal I am a bit confused with your selection of words. So you do not experience NFStream being slow but your main problem is a massive number of files that must be processed sequentially?

Could you please describe what behaviour would you expect from NFStream?

**Comment by SunEternal** [comment]
For example, NFStream can take a few seconds to process a large PCAP file of 1GB, which is great. However, processing a small PCAP file of 1M also takes a few seconds. So when I need to process hundreds of thousands of small PCAP files, it takes a long time. I wonder if there is a way to process a large number of PCAP files in batch. Thank you very much for your patience.

**Comment by drnpkr** [comment]
I am afraid NFStream is currently not suitable for this specific goal. What you could do is to write a script (just a couple of lines) that iterates through all PCAP files in your folder and process them sequentially. This way you, do not need to manually run the program with different file names.

**Comment by SunEternal** [comment]
Thank you very much for your answer, I think I need to try to solve it with multiple processes
