### ISSUE TITLE
Get timestamp for each source Ip ?

### ISSUE THREAD

**Issue by adendogar** [nfstream/nfstream#132]
Hi 
I am try to get timestamp associated with each source IP .can you please give me an example how can i use the NFPlugin for that purpose ?

**Comment by drnpkr** [comment]
I would treat each packet as a single-packet flow (there is an example for such an NFplugin here on GitHub) and would focus on the flow start feature (column). That would do the trick. I would not apply this in production though.

**Comment by adendogar** [comment]
Can you please share a code example ?

**Comment by drnpkr** [comment]
Check the flow slicer NFplugin example here: https://nfstream.org/docs/api

**Comment by adendogar** [comment]
but flow slicer will force NFStream to expire each flow that reaches a packet count limit. my target is to get the timestamp . how this will help me ?

**Comment by adendogar** [comment]
<img width="673" alt="Screenshot 2022-08-24 at 3 57 36 PM" src="https://user-images.githubusercontent.com/78276661/186511485-f54e36ff-c16f-4fdb-91ef-c8e072f3367c.png">

**Comment by adendogar** [comment]
similar to this

**Comment by drnpkr** [comment]
If you set packet limit to 1, each row is going to correspond to a flow containing statistics about one packet, including the source IP and the flow start = timestamp. You get all the info you want. That's how it is going to help you.

**Comment by adendogar** [comment]
Hi i have followed the steps but still not getting the timestamp. can you please share the exact code with me ?
