### ISSUE TITLE
Wavelet features plugin

### ISSUE THREAD

**Issue by finloop** [nfstream/nfstream#137]
Hi! Thanks for writing NFStream I'm using it for my thesis, and it is a great tool for feature generation. 

## Plugin idea
I've come across a paper: "Efficient and robust feature extraction and selection for traffic classification" https://arxiv.org/abs/2205.05628 and in this paper they show that wavelet features are great for some ML tasks. So I thought that I could implement a plugin that would calculate them. But to do that: 

I need to split expire flow after exactly X seconds or less. From what I understand, `active_timeout` does that?

**Comment by aouinizied** [comment]
Thanks. Yes, active_timeout is what you need. Do not hesitate to contribute with a  PR once your plugins implemented.

Zied
