### ISSUE TITLE
Can't support to parser ".pcapng" file?

### ISSUE THREAD

**Issue by Pau1code** [nfstream/nfstream#139]
I noted that your "Release V6.2.6" already supports parsing `.pcapng` files. Now, my nfstream is 6.5.2, and dpkt is1.9.8.
Unfortunately, I encountered the bug shown in the following figure.
![image](https://user-images.githubusercontent.com/33210080/192732263-3910dbba-ca94-4d30-b5f4-d3e84970f874.png)

**Comment by aouinizied** [comment]
@Pau1code Thanks for reporting, can you share a pcapng file where you encounter this issue, also the script you use in order to reproduce.

Thanks

**Comment by Pau1code** [comment]
> 

sorry, I checked my script carefully and found that I had made a mistake in the file path. Now, everything is ok, thank you!
