### ISSUE TITLE
List type is not preserved after `to_pandas` method.

### ISSUE THREAD

**Issue by finloop** [nfstream/nfstream#140]
**Describe the bug**

List type is not preserved after using `to_pandas` method (possibly due to conversion to csv) and is converted to `str`.

**To Reproduce**

```python
from nfstream import NFStreamer, NFPlugin

class TestListPlugun(NFPlugin):
    def on_init(self, packet, flow):
        flow.udps.list = [1, 2, 3]

streamer = NFStreamer(source="facebook.pcap", udps=TestListPlugun())

df = streamer.to_pandas()

print(df["udps.list"][0], type(df["udps.list"][0]))
```
prints: `[1, 2, 3] <class 'str'>`

**Expected behavior**

The type should be preserved:
`[1, 2, 3] <class 'list'>`

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Pop!_OS 22.04 LTS x86_64
 - Python version: Python 3.10.6
 - NFStream version: 6.5.1

**Additional context**

Before `to_pandas` the type is correct:

```python
for flow in streamer: # Work also with to_pandas, to_csv
   print(flow.udps.list, type(flow.udps.list))
   break
```
prints: `[1, 2, 3] <class 'list'>`

I think that it happens because conversion to csv does not preserve list types in pandas, and `to_pandas` method uses them:

https://github.com/nfstream/nfstream/blob/3a2c273bf3574a940ec34ebc3e1bb0845350946a/nfstream/streamer.py#L506-L521

**Possible solution**
Use a different storage format (like json) that preserves them. I'll probably submit a PR soon.

**Comment by aouinizied** [comment]
@finloop Yes this behavior is due to CSV temporary file involved in Pandas conversion.
You can still convert your pandas columns to the desired type.
Do not hesitate to open a PR if you have an improvement for that (JSON or whatever other serialization).

Zied
