### ISSUE TITLE
ImportError: DLL load failed while importing _lib_engine: The specified module could not be found.

### ISSUE THREAD

**Issue by Cheb-Zh** [nfstream/nfstream#145]
Hey,

I always get this error, when I import the nfstream package.   I'm not sure where is the problem comes from? Thank you.
**ImportError: DLL load failed while importing _lib_engine: The specified module could not be found.**

**Comment by aouinizied** [comment]
@Cheb-Zh Can you please provide us with some additional information about your context in order to help you?

* nfsteam version.
* how it was installed.
* your system OS and architecture.
* a complete error log.

Thanks
Zied

**Comment by debugpro** [comment]
1.nfstream-6.5.3
2.pip install nfstream
3.windows 10 professional 
4.File "C:\Python39\lib\site-packages\nfstream\__init__.py", line 17, in <module>
    from .streamer import NFStreamer
  File "C:\Python39\lib\site-packages\nfstream\streamer.py", line 25, in <module>
    from .meter import meter_workflow
  File "C:\Python39\lib\site-packages\nfstream\meter.py", line 16, in <module>
    from .engine import create_engine, setup_capture, setup_dissector, activate_capture
  File "C:\Python39\lib\site-packages\nfstream\engine\__init__.py", line 16, in <module>
    from .engine import create_engine, setup_capture, setup_dissector, activate_capture
  File "C:\Python39\lib\site-packages\nfstream\engine\engine.py", line 16, in <module>
    from _lib_engine import ffi, lib
ImportError: DLL load failed while importing _lib_engine: 找不到指定的模块。

**Comment by qy201706** [comment]
I got the same issue. Have you get over it?

**Comment by qy201706** [comment]
You just need to install the wireshark. And the error will disappear.

**Comment by SCU-Yecheng** [comment]
> You just need to install the wireshark. And the error will disappear.

I already have wireshark, my os is win10, python 3.8.10 64-bit.

**Comment by chendianhuiyi** [comment]
> > 你只需要安装wireshark。并且错误将会消失。
> 
> 我已经有wireshark，我的操作系统是win10，python 3.8.10 64位。

Try to install Winpcap.
