### ISSUE TITLE
NFlow NFPacket's ip_packet losses ending bytes!

### ISSUE THREAD

**Issue by lowoodz** [nfstream/nfstream#155]
nfstream-version: 6.5.2
Source code:
```
def nfpacket_to_tgpacket(nf_obj):
    ip_packet = bytes(bytearray(nf_obj.ip_packet).copy())
    return ip_packet

class FlowTraffic(NFPlugin):
    def on_init(self, packet, flow):
        # flow creation with the first packet
        flow.udps.packets = []
        pkt = nfpacket_to_tgpacket(packet)
        flow.udps.packets.append(pkt)

    def on_update(self, packet, flow):
        # flow update with each packet belonging to the flow
        pkt = nfpacket_to_tgpacket(packet)
        flow.udps.packets.append(pkt)

nf_streamer = NFStreamer(source=pcap_file,
                             decode_tunnels=True,
                             bpf_filter=None,
                             promiscuous_mode=True,
                             snapshot_length=1536,
                             idle_timeout=120,
                             active_timeout=1800,
                             # Bytes related features accounting mode:
                             # (0: Link layer, 1: IP layer, 2: Transport layer, 3: Payload)
                             accounting_mode=0,
                             udps=FlowTraffic(), # 	Specify user defined NFPlugins
                             n_dissections=40, # Number of per flow packets to dissect for L7 visibility feature (nDPI)
                             statistical_analysis=True, # Enable/Disable post-mortem flow statistical analysis
                             splt_analysis=20, # Specify the sequence of first packets length for early statistical analysis
                             n_meters=8, # 	Specify the number of parallel metering processes
                             #max_nflows=0,
                             performance_report=0,
                             system_visibility_mode=0,
                             system_visibility_poll_ms=100)
```
screen-shot (the ip_packet in fact is 1500 bytes, but only got 1486 bytes):
![nfstream-bug](https://user-images.githubusercontent.com/3724423/212871876-a91d2603-dc68-42fb-90e8-e45f422b2922.jpg)

The source pcap:
[TLS.WindowsUpdate_good_flow.pcap.zip](https://github.com/nfstream/nfstream/files/10433834/TLS.WindowsUpdate_good_flow.pcap.zip)

**Comment by aouinizied** [comment]
@lowoodz  Thanks for reporting. Can you provide more information about the context?
Whats is the expected behavior and which result do you obtain?
Also a pcap file would help.

Zied

**Comment by lowoodz** [comment]
> 

Yes, I have uploaded the screen shot and the bug-triggering pcap. Thank you for quickly reply!

**Comment by aouinizied** [comment]
@lowoodz 
When I look closely to your packet. I see that the caplen is 1500 and the len is 1514.
This means that you actually have a truncated packet up to 1500.
Then, what you observe with nfstream is normal as it does 1500 - 14 = 1486.

https://stackoverflow.com/questions/1491660/pcap-struct-pcap-pkthdr-len-vs-caplen

Thanks,
Zied

**Comment by lowoodz** [comment]
@aouinizied do you mean that the original packet is 1514, but only 1500 have been captured? But I still can't understand why nfstream gives only 1486 bytes? 
The result is nfstream get 14 byte lossed!
<img width="1156" alt="Screen Shot 2023-01-20 at 10 55 45 PM" src="https://user-images.githubusercontent.com/3724423/213729144-1540bcea-a362-4d4f-8ded-bdd80dfb7f7c.png">

**Comment by lowoodz** [comment]
@aouinizied Can you please answer my question, is there any way to get all the bytes captured? 
And an open question, if I want to parse captured network traffic in memory, how can I do that with nfstream or, do you have any recommendations?

**Comment by aouinizied** [comment]
@lowoodz As stated in my previous answer. You captured packed in truncated to 1500. Ip packet contained bytes starting from the IP header so it is normal to have 1486 (1500 - 14) bytes.

**Comment by lowoodz** [comment]
@aouinizied I can understand what you mean but, from the wireshark parsed result, the Ethernet len is 1514, IP len is 1486 (1500 - 14) bytes. I also check this by using dpkt, this 5th packet's len is also 1514. Please check it again...
![lanxin_20230131090948](https://user-images.githubusercontent.com/3724423/215633992-53daa254-7ff6-4d92-94c9-e47991bef2f5.png)

**Comment by drnpkr** [comment]
@lowoodz Let me clarify this. NFStream measures size in two ways. One way is to calculate the actual size obtained through the raw packet. The second way is by looking into the header structure and pulling out the appropriate values exactly as you showed here. 

Nonetheless, if you want the correct size, just switch the 'ip_packet' to 'ip_size.'

**Comment by aouinizied** [comment]
@lowoodz The ip_size reported by nfstream is correct in your case. Same as the one displayed by wireshark as we read it from te header. However the bytes in ip_packet are truncated due to your capture setting.

**Comment by aouinizied** [comment]
@lowoodz  I will reinvestigate it and keep you informed.

**Comment by lowoodz** [comment]
@aouinizied Thank you!

**Comment by aouinizied** [comment]
@lowoodz let's simplify things. I picked out one picket from your file ([debug_size.zip](https://github.com/nfstream/nfstream/files/10581273/debug_size.zip)) and will answer you based on that one.

Let's look at he output of the following code snippet:

```python
from nfstream import NFStreamer, NFPlugin

class NFPacketPrint(NFPlugin):
    def on_init(self, packet, flow):
        print("raw_size={}".format(packet.raw_size))
        print("ip_size={}".format(packet.ip_size))
        print("len(ip_packet)={}".format(len(packet.ip_packet)))

for flow in NFStreamer("debug_size.pcap", udps=NFPacketPrint()):
    pass
```
```shell
raw_size=1514
ip_size=1500
len(ip_packet)=1486
```

* The raw size is extracted from the pcap packet header (len field)
* The ip_size is equal to 1514 - 14 = 1500 which is OK.
* You expect len(ip_packet) to be 1500 however it's 1486.

This is due to you capture length. While the raw size indicates 1514, you captured the packet with 1500 limit. When we extract the bytes, we eliminate 14 bytes for ethernet header and the remaining bytes are equal to 1486.

Look at the output of `capinfos

```shell
capinfos debug_size.pcap
```

```shell
File name:           ../debug_size.pcap
File type:           Wireshark/tcpdump/... - pcap
File encapsulation:  Ethernet
File timestamp precision:  microseconds (6)
Packet size limit:   file hdr: 1500 bytes
Number of packets:   1
File size:           1 554 bytes
Data size:           1 514 bytes
Capture duration:    0,000000 seconds
First packet time:   2022-12-06 09:53:45,366207
Last packet time:    2022-12-06 09:53:45,366207
Data byte rate:      0 bytes/s
Data bit rate:       0 bits/s
Average packet size: 1514,00 bytes
Average packet rate: 0 packets/s
SHA256:              98ef9ba9d62b72c2f8306cd547047381330e2544232573364513c094ee3fef9f
RIPEMD160:           661d70abefd0c56833db39dd99f90b81559cfdea
SHA1:                274e63ac84185f9bd96338e284ca11463f98a5d3
Strict time order:   True
Number of interfaces in file: 1
Interface #0 info:
                     Encapsulation = Ethernet (1 - ether)
                     Capture length = 1500
                     Time precision = microseconds (6)
                     Time ticks per second = 1000000
                     Number of stat entries = 0
                     Number of packets = 1
```

As you can see Packet size limit is 1500.

Hope this helps to clarify things for you.

Zied

**Comment by lowoodz** [comment]
@aouinizied I got it, there is an misalignment in the pcap, the header says snap len is 1500, but in each packet the acutual size is bigger than this (e.g. 1514), because I haven't set snaplen when create dpkt.pcap.Writer object! Thank you so much! : )
