### ISSUE TITLE
packets with same 'flow_key' of already expired flows will (unwillingly) create a new flow

### ISSUE THREAD

**Issue by francktoub** [nfstream/nfstream#171]
Hi,

According to the documentation, when using the “flow slicer” plugin, flows will expire after a specific number of packets. However, any new packet with the same ‘flow_key’ will create a new flow. This means that the outputted csv file/dataframe may have several rows with the same ‘flow_key’. How can I avoid this behavior?

In other words, if I set the limit of the flow slicer to be 10 packets, I want nfstream to discard any packet (having the same ‘flow_key’) after the 10th one and not create a new flow.

Please note that my source isn’t a .pcap file but bond0.

I hope this helps! Let me know if you have questions.

Thanks

**Comment by drnpkr** [comment]
Hi @francktoub, 

This is the desired behaviour of flow metering. Aggregate packets with the same flow key into flows. 

If you want to achieve the described behaviour, you gonna need to filter such packets out once the original flow hits the count of 10 packets. Certainly, this won't be a well scalable solution, but should do the trick.

**Comment by aouinizied** [comment]
@francktoub You can maintain a hashset within the Plugin and then add a check for existence at each of the plugin stage. This will allow you to not run the plugin on a flow that was already processed.

Zied

**Comment by francktoub** [comment]
thanks both @drnpkr and @aouinizied for the quick answer!

@aouinizied just to be sure I've understood you:
1. by "plugin stage" you mean 'on_init', 'on_update' and 'on_expire' right?
2. by "already processed" you mean that the flow the new packet belongs to has alreday been expired by the flow slicer?
3. I'll have to check for existence at each stage of each pluign?
4. Where to create the hashset? in the flow slicer?
5. I am supposed to add the flow_keys to the hashset in the 'on_expire' of fthe flow slicer right?

Thanks again!
