### ISSUE TITLE
The precision of packet timestamps in session flows

### ISSUE THREAD

**Issue by vsvs5667** [nfstream/nfstream#178]
I'm having an issue with the precision of packet timestamps in session flows using the NFStream library. I need higher precision timestamps (at the millisecond level) to calculate packet time intervals, but NFStream only provides timestamps at the second level. Could you please advise on how I can solve this issue?

**Comment by drnpkr** [comment]
What makes you think the times are in seconds? It is quite clear from the documentation that NFStream measures the features in milliseconds: https://www.nfstream.org/docs/api
