### ISSUE TITLE
Active_timeout and idle_timeout not behaving as expected

### ISSUE THREAD

**Issue by gerivives** [nfstream/nfstream#193]
**Describe the bug**
Theoretically, if no packets in either direction for a particular flow are received within idle_timeout, this flow should expire on a live traffic capture. However, this is not the behaviour that I am experiencing since it takes longer for these flows to expire (generally, around 1 to 2 minutes). Moreover, when using TCP I expected the flow to expire when the 3-way FYN handshake takes place, however this is not the case either. Am I missing something? I want to use the post-mortem features to detect anomalies in traffic using a ML model; however, it is not feasible now since it takes too long to be able reach the on_expire method.

**To Reproduce**
1. Run a live traffic capture
2. Set idle_timeout to 5 and active_timeout to 120
4. After 5 seconds with no new packets, the flow should expire. However, this is not the case.

**Expected behavior**
Flow expires on idle_timeout seconds after not having received packets in either direction or after the 3-way FYN handshake taking place for TCP.

**Desktop (please complete the following information):**
 - OS: 20.04.1-Ubuntu
 - Python version 3.8
 - NFStream version 6.5.3

**Comment by aouinizied** [comment]
It is expected. The internal timer is updated by received packets. So you need at least one packet with valid timestamp to trigger expiration based on timeouts. Natural expiration for TCP is not supported. It is simple however to implement it as a Plugin.
