### ISSUE TITLE
System memory problem in some pcap files

### ISSUE THREAD

**Issue by XDDDDDG** [nfstream/nfstream#24]
When I use nfstream to process some pcap files, I have some memory problems
The performance is that the system memory continues to rise to a high value, and then it is killed. Processing packages that are much larger than these PCAPs will not cause memory usage problems of this size.
could you give me some suggestions？

**Comment by aouinizied** [comment]
@XDDDDDG memory usage is directly related to the amount of flow active in the cache.
So it's normal that it's not correlated to the size of the pcap. Example:
* 1 pcap with 1 Terabyte size. containing only 4 flows (let's say 4 huge file transfer).  Despite being a large file, nfstream will treat it as 4 cache entries. (very small memory footprint).
* Second example with 10M packets generated at the same second and each packet belongs to a single flow. nfstream will create 10M cache entries and memory usage will be larger.
In such a case, tuning the inactive timeout may reduces the amount of memory observed, for example, set it to 5 seconds.

Zied
