### ISSUE TITLE
How to get MAC address of flow

### ISSUE THREAD

**Issue by missyoyo** [nfstream/nfstream#25]
Hello:
   May I know how to get NIC MAC Address of flow since I can find any MAC address in NFEntry,Thank you.

**Comment by drnpkr** [comment]
Hi there!

I think you need to understand here that NFStream is an IP flow measurement tool. The flows are created based on the captured packets (typical 5-tuple). As such, there no information included from the lowest layers.

I hope this provides some clarification for you.

**Comment by aouinizied** [comment]
@missyoyo currently layer 2 informations are not available as nfstream is designed to be an IP measurement framework.
@drnpkr Maybe we will add such feature in next release as it can be relevant is several cases (Device Manufacturer, etc.)

BR,
Zied

**Comment by missyoyo** [comment]
That is very kind if you can add L2 informations, MAC address is a good way to know traffic is outbound or inbound,So we can know bi-direction bandwidth。
