### ISSUE TITLE
Performance of nfstream

### ISSUE THREAD

**Issue by missyoyo** [nfstream/nfstream#26]
hello:
    May I know if we try to default "NFEntry" from network interface,How many packets per second nfstream can support(Do not drop packet). OR is there some way to  increased performance， For example: MMAP、PFring、DPDK?
thank you.

**Comment by aouinizied** [comment]
Dropped packets are not reported. The next planned release will provide performance statistics and computation will be distributed across several cores (faster). I will keep this issue open until the next release. You will be able to measure the drop rate on your network.

**Comment by missyoyo** [comment]
That is very good if nfstream can use multiple cores.I see nfstream base on libpcap,And libpcap have already add DPDK support with master branch:
[https://github.com/the-tcpdump-group/libpcap/pull/790](url)
I have test tcpdump can dump DPDK interface buy use libpcap support.
I have try to test nfstream with DPDK, by change nfstream git config file(clone libpcap master branch and configure with dpdk support), I can configure and install nfstream but can not run it.I think it may be an easy way to increase performance if can use libpcap DPDK version. and that is very kind of you if can add drop packets  report,thank you.

**Comment by aouinizied** [comment]
@missyoyo Thanks for the information.
* We redesigned the metering architecture and this introduces up to *12 speed gain (depending on how traffic is distributed across cores and the number of available cores). This improvement is confirmed both on Pypy and CPython and now the gap between these interpreters decreased as we passed the maximum of computation to native code.
* Regarding libpcap with dpdk support. In fact, it's an interesting option. We need to check how to interface with it with our parallelization paradigm and adapt if needed. But actual performance (v6.0 not released yet) will be sufficient for major use cases.
* I will try to add MAC address and rewrite part of the doc as we changed APIs and we will release soon.
* Do not hesitate to open a PR if you want to add some features.

Zied

**Comment by missyoyo** [comment]
@aouinizied Thank you for your update
Here is my try step:
1.Download DPDK and make install to default localtion"/usr/local".
2.Change nfstream libpacp setup.py and add configure opeions "--with-dpdk=/usr/local"
3.Install nfstream form source code.

Here is my error message if usefull:

cannot load library '/usr/local/lib/python3.6/site-packages/nfstream/observer_cc.so': /usr/local/lib/python3.6/site-packages/nfstream/observer_cc.so: undefined symbol: rte_cycles_vmware_tsc_map.  Additionally, ctypes.util.find_library() did not manage to locate a library called '/usr/local/lib/python3.6/site-packages/nfstream/observer_cc.so'

sha1sum /usr/local/lib/python3.6/site-packages/nfstream/observer_cc.so
035117df933913a7abc8fa1cdec1687c26fdd604  /usr/local/lib/python3.6/site-packages/nfstream/observer_cc.so

Thank you

**Comment by missyoyo** [comment]
@aouinizied 
May I know how to change setup.py use libpcap.so instead of use "libpcap.a"
# compile libpcap and ship it with observer
    # we compile libpcap instead of copying the .so from to ensure 1.9.1 version on both mac OS and Linux
    subprocess.check_call(['git', 'clone',
                           'https://gitee.com/missyoyo/libpcap'])
    os.chdir('libpcap/')
    subprocess.check_call(['./configure', 'CC={}'.format(platform_compiler), '--enable-ipv6', '--disable-universal',
                           '--enable-dbus=no', '--without-libnl'])
    subprocess.check_call(['make'])
    os.chdir('..')
    subprocess.check_call([platform_compiler, '-shared', '-o', 'observer_cc.so', '-g', '-fPIC', '-DPIC', '-O2', '-Wall',
                           'observer_cc.c', 'libpcap/libpcap.a'])

Thank you.

**Comment by aouinizied** [comment]
@missyoyo check git blame and you will have it in history as it was the previous method used.
Note that v6.0.1 is released and introduces performance improvement.
