### ISSUE TITLE
Does nfstream support pcap dump function by ip or port etc.

### ISSUE THREAD

**Issue by IAMABOY** [nfstream/nfstream#27]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Ubuntu]
 - Python version [e.g. 3.6, 3.7]

**Additional context**

**Comment by aouinizied** [comment]
@IAMABOY No, nfstream does not support dump feature.

Best regards,
Zied
