### ISSUE TITLE
Does json format output has moved now?

### ISSUE THREAD

**Issue by missyoyo** [nfstream/nfstream#30]
Hi:
   I am test last release nfstream 6.02, I only see:
    def keys(self):
    def values(self):
from flow.py, can not see
  def to_json(self):
is to_json output has removed now,It is a nice feature,Please keep that if possible. Thank you.

**Comment by aouinizied** [comment]
@missyoyo You can build a JSON simply by doing the following:

```python
import json

# For each flow, convert it to json.
json.dumps(dict(zip(flow.keys(), flow.values())))
```

Zied

**Comment by missyoyo** [comment]
@aouinizied HI:
    I have test your code and work good. Thank you for your help.
