### ISSUE TITLE
Can ouput performance report every 5 minutes

### ISSUE THREAD

**Issue by missyoyo** [nfstream/nfstream#31]
I see current performance report  output only when program end or exit.
Can nfstream send performance report with intervals, For example: 5 minutes, So we can know  burst traffic or need by more powerfull hardware in time.
If possiable,one sinlge event performance report is perfered(or one json report)
Thank you.

**Comment by aouinizied** [comment]
Hi,

You must upgrade to version 6.1.0 where we implemented this feature for live capture.

* performance_report=N will print every N seconds performance [**metrics**](https://github.com/nfstream/nfstream/blob/master/assets/PERFORMANCE_REPORT.md).
* To limit drops, you must set n_meters to 0 (default value). Note that processes will consume CPU only when packets are there (No busy-wait anymore).
* NFStream now supports AF_PACKETv3 + FANOUT on Linux machines.
* Before considering more powerful hardware, make sure to test with Pypy3 instead od CPython as it is faster.

Zied
