### ISSUE TITLE
json output not work in 6.1.3

### ISSUE THREAD

**Issue by missyoyo** [nfstream/nfstream#36]
Hello:
   I have test json output by nfstream version 6.1.3 and json output seems not work,I have test on Centos 8 and Ubuntu 18.04.
print flow is work
print(flow.values()) output below:
['id', 'expiration_id', 'src_ip', 'src_ip_is_private', 'src_port', 'dst_ip', 'dst_ip_is_private', 'dst_port', 'protocol', 'ip_version', 'vlan_id', 'bidirectional_first_seen_ms', 'bidirectional_last_seen_ms', 'bidirectional_duration_ms', 'bidirectional_packets', 'bidirectional_bytes', 'src2dst_first_seen_ms', 'src2dst_last_seen_ms', 'src2dst_duration_ms', 'src2dst_packets', 'src2dst_bytes', 'dst2src_first_seen_ms', 'dst2src_last_seen_ms', 'dst2src_duration_ms', 'dst2src_packets', 'dst2src_bytes', 'application_name', 'application_category_name', 'application_is_guessed', 'requested_server_name', 'client_fingerprint', 'server_fingerprint', 'user_agent', 'content_type']
print(flow.keys()) output below:
[27, 1, '10.10.10.72', 1, 12403, '10.10.10.6', 1, 443, 6, 4, 0, 1602662725117, 1602662726115, 998, 4, 379, 1602662725117, 1602662726115, 998, 3, 254, 1602662725131, 1602662725131, 0, 1, 125, 'TLS', 'Web', 1, '', '', '', '', '']
json.dumps(dict(zip(flow.keys(), flow.values()))) get no output
I have some test code below:
import json
a=['id', 'expiration_id', 'src_ip', 'src_ip_is_private', 'src_port', 'dst_ip', 'dst_ip_is_private', 'dst_port', 'protocol', 'ip_version', 'vlan_id', 'bidirectional_first_seen_ms', 'bidirectional_last_seen_ms', 'bidirectional_duration_ms', 'bidirectional_packets', 'bidirectional_bytes', 'src2dst_first_seen_ms', 'src2dst_last_seen_ms', 'src2dst_duration_ms', 'src2dst_packets', 'src2dst_bytes', 'dst2src_first_seen_ms', 'dst2src_last_seen_ms', 'dst2src_duration_ms', 'dst2src_packets', 'dst2src_bytes', 'application_name', 'application_category_name', 'application_is_guessed', 'requested_server_name', 'client_fingerprint', 'server_fingerprint', 'user_agent', 'content_type']
b=[27, 1, '10.10.10.72', 1, 12403, '10.10.10.6', 1, 443, 6, 4, 0, 1602662725117, 1602662726115, 998, 4, 379, 1602662725117, 1602662726115, 998, 3, 254, 1602662725131, 1602662725131, 0, 1, 125, 'TLS', 'Web', 1, '', '', '', '', '']
json.dumps(dict(zip(a,b)))
output below:
'{"id": 27, "expiration_id": 1, "src_ip": "10.10.10.72", "src_ip_is_private": 1, "src_port": 12403, "dst_ip": "10.10.10.6", "dst_ip_is_private": 1, "dst_port": 443, "protocol": 6, "ip_version": 4, "vlan_id": 0, "bidirectional_first_seen_ms": 1602662725117, "bidirectional_last_seen_ms": 1602662726115, "bidirectional_duration_ms": 998, "bidirectional_packets": 4, "bidirectional_bytes": 379, "src2dst_first_seen_ms": 1602662725117, "src2dst_last_seen_ms": 1602662726115, "src2dst_duration_ms": 998, "src2dst_packets": 3, "src2dst_bytes": 254, "dst2src_first_seen_ms": 1602662725131, "dst2src_last_seen_ms": 1602662725131, "dst2src_duration_ms": 0, "dst2src_packets": 1, "dst2src_bytes": 125, "application_name": "TLS", "application_category_name": "Web", "application_is_guessed": 1, "requested_server_name": "", "client_fingerprint": "", "server_fingerprint": "", "user_agent": "", "content_type": ""}'

seems work in alone python3 code. But not work in nfstream, would you like to check it,Thank you.

**Comment by drnpkr** [comment]
Hey!

Did you try checking the variable types? I mean, try comparing what is the output of the following:

`a = flow.values()`
`b = flow.keys()`
`type(a)`
`type(b)`

And then check the same with your test code.

**Comment by missyoyo** [comment]
Hi drnpkr:
   I have test both flow.values() and flow.keys() type is str. I have add print() to json.dumps(dict(zip(flow.keys(), flow.values()))) seems get output,
{"id": 7, "expiration_id": 1, "src_ip": "10.10.10.78", "src_ip_is_private": 1, "src_port": 22, "dst_ip": "10.10.10.72", "dst_ip_is_private": 1, "dst_port": 13881, "protocol": 6, "ip_version": 4, "vlan_id": 0, "bidirectional_first_seen_ms": 1602664919014, "bidirectional_last_seen_ms": 1602664919076, "bidirectional_duration_ms": 62, "bidirectional_packets": 8, "bidirectional_bytes": 4406, "src2dst_first_seen_ms": 1602664919014, "src2dst_last_seen_ms": 1602664919035, "src2dst_duration_ms": 21, "src2dst_packets": 5, "src2dst_bytes": 4226, "dst2src_first_seen_ms": 1602664919028, "dst2src_last_seen_ms": 1602664919076, "dst2src_duration_ms": 48, "dst2src_packets": 3, "dst2src_bytes": 180, "application_name": "SSH", "application_category_name": "RemoteAccess", "application_is_guessed": 1, "requested_server_name": "", "client_fingerprint": "", "server_fingerprint": "", "user_agent": "", "content_type": ""}
Maybe json.dumps not to stout?

**Comment by drnpkr** [comment]
That's correct. Without `print()` you would not see any output. The same is with `type()`. 

I assume you mix using the python interpreter and the code you develop. In the interpreter, you will get the desired output without explicitly printing the variables. In your code, you have to explicitly print the variable out.

**Comment by missyoyo** [comment]
@drnpkr 
Thank you for your help and I also do some performance test and I will open another ticket soon.

**Comment by aouinizied** [comment]
@missyoyo Glad that it's solved. For performances test, do not hesitate to add detailed description about environment, machine, versions etc.
