### ISSUE TITLE
Performance test with version 6.1.3

### ISSUE THREAD

**Issue by missyoyo** [nfstream/nfstream#37]
Hello:
   I have some performance test with nfstream 6.1.3.My test env is  16 VCPU(Intel(R) Xeon(R) CPU X5670 @ 2.93GHz) with 16GB RAM and NIC is Intel X520 10Gbps
When I try to read pcap form file(RAM disk,Maybe fast), I see nfsteam can support 0.4Mpps(I have change output interval to 1 second).
![图片](https://user-images.githubusercontent.com/19371588/95968297-db4e4380-0e3f-11eb-86cb-22fd337a8808.png)
When I try to read packet form NIC alive.Get a lot of packet lost when only send 02.Mpps
![图片](https://user-images.githubusercontent.com/19371588/95968978-be664000-0e40-11eb-9a92-63f12c1bfab4.png)
![图片](https://user-images.githubusercontent.com/19371588/95969019-cb832f00-0e40-11eb-96f7-23308b03ef6c.png)
Are we need addtion config to enable AF_PACKETV3 for NIC live captrue?
Thank you.

**Comment by missyoyo** [comment]
By the way.I am using pypy.

**Comment by missyoyo** [comment]
With 0.1Mpps send by packet generater I get few packet lost
![图片](https://user-images.githubusercontent.com/19371588/95969826-cc689080-0e41-11eb-8a7c-d8af45b46ff2.png)
![图片](https://user-images.githubusercontent.com/19371588/95969971-fe79f280-0e41-11eb-9e3b-5661575d9bed.png)

**Comment by aouinizied** [comment]
@missyoyo can you provide full NFStreamers options used and full log of performances (including load_per_meter)?

**Comment by missyoyo** [comment]
I am use default option
![图片](https://user-images.githubusercontent.com/19371588/95970854-038b7180-0e43-11eb-816f-23042d3d733d.png)
01Mpps full logs:
{"flows_expired": 715, "packets_processed": 65017732, "packets_ignored": 1, "packets_dropped_filtered_by_kernel": 63, "meters_packets_processing_balance": [65017732]}
{"flows_expired": 716, "packets_processed": 65116997, "packets_ignored": 1, "packets_dropped_filtered_by_kernel": 63, "meters_packets_processing_balance": [65116997]}
{"flows_expired": 717, "packets_processed": 65216259, "packets_ignored": 1, "packets_dropped_filtered_by_kernel": 63, "meters_packets_processing_balance": [65216259]}
{"flows_expired": 718, "packets_processed": 65315524, "packets_ignored": 1, "packets_dropped_filtered_by_kernel": 63, "meters_packets_processing_balance": [65315524]}
{"flows_expired": 719, "packets_processed": 65414787, "packets_ignored": 1, "packets_dropped_filtered_by_kernel": 63, "meters_packets_processing_balance": [65414787]}
{"flows_expired": 720, "packets_processed": 65514050, "packets_ignored": 1, "packets_dropped_filtered_by_kernel": 63, "meters_packets_processing_balance": [65514050]}

**Comment by drnpkr** [comment]
please show us what `lscpu` returns to you
also, please show us the output of `ethtool -i <your-nic>`, I assume you did not use the latest ixgbe driver.

**Comment by drnpkr** [comment]
One additional thing, you mention vCPU, so I suppose, you use some sort of virtualization. Is it VMware? I recommend you set the core mapping properly into your VM.

**Comment by missyoyo** [comment]
[root@localhost ~]# lscpu
Architecture:        x86_64
CPU op-mode(s):      32-bit, 64-bit
Byte Order:          Little Endian
CPU(s):              16
On-line CPU(s) list: 0-15
Thread(s) per core:  1
Core(s) per socket:  1
Socket(s):           16
NUMA node(s):        2
Vendor ID:           GenuineIntel
CPU family:          6
Model:               44
Model name:          Intel(R) Xeon(R) CPU           X5670  @ 2.93GHz
Stepping:            2
CPU MHz:             2926.000
BogoMIPS:            5852.00
Hypervisor vendor:   VMware
Virtualization type: full
L1d cache:           32K
L1i cache:           32K
L2 cache:            256K
L3 cache:            12288K
NUMA node0 CPU(s):   0-7
NUMA node1 CPU(s):   8-15
Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss syscall nx rdtscp lm constant_tsc arch_perfmon nopl xtopology tsc_reliable nonstop_tsc cpuid pni pclmulqdq ssse3 cx16 sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes hypervisor lahf_lm pti ssbd ibrs ibpb stibp tsc_adjust arat flush_l1d arch_capabilities



[root@localhost ~]# ethtool ens192
Settings for ens192:
	Supported ports: [ ]
	Supported link modes:   10000baseT/Full 
	Supported pause frame use: No
	Supports auto-negotiation: No
	Supported FEC modes: Not reported
	Advertised link modes:  Not reported
	Advertised pause frame use: No
	Advertised auto-negotiation: No
	Advertised FEC modes: Not reported
	Speed: 10000Mb/s
	Duplex: Full
	Port: Other
	PHYAD: 0
	Transceiver: internal
	Auto-negotiation: off
	Current message level: 0x00000007 (7)
			       drv probe link
	Link detected: yes
[root@localhost ~]# ethtool -i ens192
driver: ixgbevf
version: 4.1.0-k-rh8.2.0
firmware-version: 
expansion-rom-version: 
bus-info: 0000:0b:00.0
supports-statistics: yes
supports-test: yes
supports-eeprom-access: no
supports-register-dump: yes
supports-priv-flags: yes

I am useing SR-IOV virual nic not pyhsical,and I test it with Vmware esxi 6.7

**Comment by aouinizied** [comment]
That's clearer. So I see that only one core is detected.
Can you provide the output of the following code?

```python
import psutil
print(psutil.cpu_count(logical=False))
print(psutil.cpu_count(logical=True))
print(psutil.Process().cpu_affinity())
```

**Comment by drnpkr** [comment]
OK, so based on the `lscpu` output I see that your VM configuration is not optimal. Set your CPU config like this:

![image](https://user-images.githubusercontent.com/12409729/95971729-dd99a900-0e11-11eb-80a1-4cfadbc4893e.png)

Now if you boot the VM again, and check the `lscpu` command, you shall see 16 cores, instead of 1 single. Then, NFStream should be able to balance the load between more than 1 core, hence reducing the drop rate.

One additional thing, I strongly recommend you upgrade to the latest Intel ixgbe driver. You need to download it from the Intel website, and manually compile it.

**Comment by missyoyo** [comment]
![图片](https://user-images.githubusercontent.com/19371588/95972461-0edf9c80-0e45-11eb-97c9-7c217ac5b4fa.png)
Thank you for you help. I will change my config and do more test then update later.

**Comment by aouinizied** [comment]
so nfstream load balance according to detected PHYSICAL cores on the host. This is done using print(psutil.cpu_count(logical=False)) and as you see only 1 core is currently detected on your setup. This can come from a issue in psutils https://github.com/giampaolo/psutil or from your config.

**Comment by aouinizied** [comment]
@missyoyo another point is regarding drop by kernel count, it's CUMULATIVE.

This means that this sequence has 0 drops.  Drops can occur at the start time of nfstream and then stabilize at 0.
{"flows_expired": 715, "packets_processed": 65017732, "packets_ignored": 1, "packets_dropped_filtered_by_kernel": 63, "meters_packets_processing_balance": [65017732]}
{"flows_expired": 716, "packets_processed": 65116997, "packets_ignored": 1, "packets_dropped_filtered_by_kernel": 63, "meters_packets_processing_balance": [65116997]}
{"flows_expired": 717, "packets_processed": 65216259, "packets_ignored": 1, "packets_dropped_filtered_by_kernel": 63, "meters_packets_processing_balance": [65216259]}
{"flows_expired": 718, "packets_processed": 65315524, "packets_ignored": 1, "packets_dropped_filtered_by_kernel": 63, "meters_packets_processing_balance": [65315524]}
{"flows_expired": 719, "packets_processed": 65414787, "packets_ignored": 1, "packets_dropped_filtered_by_kernel": 63, "meters_packets_processing_balance": [65414787]}
{"flows_expired": 720, "packets_processed": 65514050, "packets_ignored": 1, "packets_dropped_filtered_by_kernel": 63, "meters_packets_processing_balance": [65514050]}

**Comment by aouinizied** [comment]
@missyoyo  Here some points you might take into consideration in addition to the above-addressed issue:
* You are using 1 second as the active and inactive timeout and this affects performance. Test with more realistic values.
* You are relying on 1 flow for the test. Even with fanout, this single flow will hit only one process. Use a more realistic testing traffic scenario (More distributed one with parallel distributed flows).
* Make sure your machine isn't running other processes when performing the test.

**Comment by missyoyo** [comment]
HI:
    I have change my vcpu setting and do 4 test,seems still get packet lost(0.1Mpps send)
1.test1,packet lost
![图片](https://user-images.githubusercontent.com/19371588/96085945-2164df00-0ef4-11eb-96c6-9e6b5bb03716.png)

**Comment by missyoyo** [comment]
2.8vcpu test2,Packet lost
![图片](https://user-images.githubusercontent.com/19371588/96086180-799be100-0ef4-11eb-85e4-1a712ad80602.png)

**Comment by missyoyo** [comment]
3.sinle flow test with interval to default,packet lost
![图片](https://user-images.githubusercontent.com/19371588/96086257-a223db00-0ef4-11eb-8479-6b3291b97f06.png)

**Comment by missyoyo** [comment]
4.test 4 with default interval and random flow send,packet lost
![图片](https://user-images.githubusercontent.com/19371588/96086343-c5e72100-0ef4-11eb-8db7-7cae23f2f744.png)

**Comment by drnpkr** [comment]
Hi missyoyo, did you upgrade the NIC driver?

**Comment by missyoyo** [comment]
Sorry, I did not, let me try that.

**Comment by missyoyo** [comment]
@drnpkr 
Hi I have update driver to new version(download for intel website),and I also change my vcpu to 6 as my pysical cpu only has 6 core 12 HT(2CPU*6core*2HT).
[root@localhost stream]# modinfo ixgbevf
filename:       /lib/modules/4.18.0-193.19.1.el8_2.x86_64/updates/drivers/net/ethernet/intel/ixgbevf/ixgbevf.ko
version:        4.9.3
license:        GPL
description:    Intel(R) 10 Gigabit Virtual Function Network Driver
author:         Intel Corporation, <linux.nics@intel.com>
rhelversion:    8.2
srcversion:     84CB9CE67FEAA472617A56E
alias:          pci:v00008086d000015B4sv*sd*bc*sc*i*
alias:          pci:v00008086d000015C5sv*sd*bc*sc*i*
alias:          pci:v00008086d000015A9sv*sd*bc*sc*i*
alias:          pci:v00008086d000015A8sv*sd*bc*sc*i*
alias:          pci:v00008086d00001564sv*sd*bc*sc*i*
alias:          pci:v00008086d00001565sv*sd*bc*sc*i*
alias:          pci:v00008086d00001530sv*sd*bc*sc*i*
alias:          pci:v00008086d00001515sv*sd*bc*sc*i*
alias:          pci:v00008086d0000152Esv*sd*bc*sc*i*
alias:          pci:v00008086d000010EDsv*sd*bc*sc*i*
depends:        
name:           ixgbevf
vermagic:       4.18.0-193.19.1.el8_2.x86_64 SMP mod_unload modversions

I have test single flow, result below:
{"flows_expired": 1, "packets_processed": 147375, "packets_ignored": 8, "packets_dropped_filtered_by_kernel": 6998, "meters_packets_processing_balance": [0, 0, 147375, 0, 0]}
{"flows_expired": 2, "packets_processed": 296291, "packets_ignored": 9, "packets_dropped_filtered_by_kernel": 9906, "meters_packets_processing_balance": [0, 0, 296291, 0, 0]}
{"flows_expired": 3, "packets_processed": 449904, "packets_ignored": 9, "packets_dropped_filtered_by_kernel": 9906, "meters_packets_processing_balance": [0, 0, 449904, 0, 0]}
{"flows_expired": 4, "packets_processed": 603121, "packets_ignored": 9, "packets_dropped_filtered_by_kernel": 9906, "meters_packets_processing_balance": [0, 0, 603121, 0, 0]}
{"flows_expired": 5, "packets_processed": 756788, "packets_ignored": 9, "packets_dropped_filtered_by_kernel": 9906, "meters_packets_processing_balance": [0, 0, 756788, 0, 0]}
{"flows_expired": 6, "packets_processed": 910234, "packets_ignored": 9, "packets_dropped_filtered_by_kernel": 9906, "meters_packets_processing_balance": [0, 0, 910234, 0, 0]}
{"flows_expired": 7, "packets_processed": 1064904, "packets_ignored": 9, "packets_dropped_filtered_by_kernel": 9906, "meters_packets_processing_balance": [0, 0, 1064904, 0, 0]}
{"flows_expired": 8, "packets_processed": 1219811, "packets_ignored": 9, "packets_dropped_filtered_by_kernel": 9906, "meters_packets_processing_balance": [0, 0, 1219811, 0, 0]}
{"flows_expired": 9, "packets_processed": 1374707, "packets_ignored": 9, "packets_dropped_filtered_by_kernel": 9906, "meters_packets_processing_balance": [0, 0, 1374707, 0, 0]}
{"flows_expired": 10, "packets_processed": 1529096, "packets_ignored": 9, "packets_dropped_filtered_by_kernel": 9906, "meters_packets_processing_balance": [0, 0, 1529096, 0, 0]}
{"flows_expired": 11, "packets_processed": 1683681, "packets_ignored": 10, "packets_dropped_filtered_by_kernel": 9906, "meters_packets_processing_balance": [0, 0, 1683681, 0, 0]}
{"flows_expired": 12, "packets_processed": 1838232, "packets_ignored": 10, "packets_dropped_filtered_by_kernel": 9906, "meters_packets_processing_balance": [0, 0, 1838232, 0, 0]}
{"flows_expired": 13, "packets_processed": 1992949, "packets_ignored": 11, "packets_dropped_filtered_by_kernel": 9906, "meters_packets_processing_balance": [0, 0, 1992949, 0, 0]}
{"flows_expired": 14, "packets_processed": 2147330, "packets_ignored": 11, "packets_dropped_filtered_by_kernel": 9906, "meters_packets_processing_balance": [0, 0, 2147330, 0, 0]}
{"flows_expired": 15, "packets_processed": 2301594, "packets_ignored": 11, "packets_dropped_filtered_by_kernel": 9906, "meters_packets_processing_balance": [0, 0, 2301594, 0, 0]}
{"flows_expired": 16, "packets_processed": 2455956, "packets_ignored": 11, "packets_dropped_filtered_by_kernel": 9906, "meters_packets_processing_balance": [0, 0, 2455956, 0, 0]}
{"flows_expired": 17, "packets_processed": 2610496, "packets_ignored": 11, "packets_dropped_filtered_by_kernel": 9906, "meters_packets_processing_balance": [0, 0, 2610496, 0, 0]}
{"flows_expired": 18, "packets_processed": 2764923, "packets_ignored": 11, "packets_dropped_filtered_by_kernel": 9906, "meters_packets_processing_balance": [0, 0, 2764923, 0, 0]}
{"flows_expired": 19, "packets_processed": 2919370, "packets_ignored": 12, "packets_dropped_filtered_by_kernel": 9906, "meters_packets_processing_balance": [0, 0, 2919370, 0, 0]}
{"flows_expired": 20, "packets_processed": 3073885, "packets_ignored": 12, "packets_dropped_filtered_by_kernel": 9906, "meters_packets_processing_balance": [0, 0, 3073885, 0, 0]}
{"flows_expired": 21, "packets_processed": 3228619, "packets_ignored": 12, "packets_dropped_filtered_by_kernel": 9906, "meters_packets_processing_balance": [0, 0, 3228619, 0, 0]}
{"flows_expired": 22, "packets_processed": 3382814, "packets_ignored": 12, "packets_dropped_filtered_by_kernel": 9906, "meters_packets_processing_balance": [0, 0, 3382814, 0, 0]}
{"flows_expired": 23, "packets_processed": 3537360, "packets_ignored": 12, "packets_dropped_filtered_by_kernel": 9906, "meters_packets_processing_balance": [0, 0, 3537360, 0, 0]}

**Comment by missyoyo** [comment]
Seems lost packet count not increase,I have a question about how many packet processed.
As first line I got:
"packets_processed": 147375
last line I got:
"packets_processed": 3537360

Is that 
(3537360-147375)/24=0.14Mpps?

**Comment by missyoyo** [comment]
@drnpkr 
I aslo have random flow test.
{"flows_expired": 70, "packets_processed": 59017, "packets_ignored": 0, "packets_dropped_filtered_by_kernel": 19174, "meters_packets_processing_balance": [13793, 15140, 15172, 14911, 1]}
{"flows_expired": 196, "packets_processed": 59017, "packets_ignored": 0, "packets_dropped_filtered_by_kernel": 19174, "meters_packets_processing_balance": [13793, 15140, 15172, 14911, 1]}
{"flows_expired": 1543, "packets_processed": 59017, "packets_ignored": 0, "packets_dropped_filtered_by_kernel": 19174, "meters_packets_processing_balance": [13793, 15140, 15172, 14911, 1]}
{"flows_expired": 5174, "packets_processed": 59017, "packets_ignored": 0, "packets_dropped_filtered_by_kernel": 19174, "meters_packets_processing_balance": [13793, 15140, 15172, 14911, 1]}
{"flows_expired": 9566, "packets_processed": 59017, "packets_ignored": 0, "packets_dropped_filtered_by_kernel": 19174, "meters_packets_processing_balance": [13793, 15140, 15172, 14911, 1]}
{"flows_expired": 17293, "packets_processed": 59017, "packets_ignored": 0, "packets_dropped_filtered_by_kernel": 19174, "meters_packets_processing_balance": [13793, 15140, 15172, 14911, 1]}
{"flows_expired": 24446, "packets_processed": 69783, "packets_ignored": 0, "packets_dropped_filtered_by_kernel": 144762, "meters_packets_processing_balance": [13793, 15140, 25938, 14911, 1]}
{"flows_expired": 31771, "packets_processed": 103981, "packets_ignored": 1, "packets_dropped_filtered_by_kernel": 560351, "meters_packets_processing_balance": [26339, 26112, 25938, 25591, 1]}
{"flows_expired": 40004, "packets_processed": 103981, "packets_ignored": 1, "packets_dropped_filtered_by_kernel": 560351, "meters_packets_processing_balance": [26339, 26112, 25938, 25591, 1]}
{"flows_expired": 48156, "packets_processed": 103981, "packets_ignored": 1, "packets_dropped_filtered_by_kernel": 560351, "meters_packets_processing_balance": [26339, 26112, 25938, 25591, 1]}
{"flows_expired": 56665, "packets_processed": 107699, "packets_ignored": 1, "packets_dropped_filtered_by_kernel": 657622, "meters_packets_processing_balance": [26339, 26112, 25938, 29309, 1]}
{"flows_expired": 64957, "packets_processed": 121491, "packets_ignored": 1, "packets_dropped_filtered_by_kernel": 921193, "meters_packets_processing_balance": [26339, 26112, 25938, 29309, 13793]}
{"flows_expired": 72860, "packets_processed": 130134, "packets_ignored": 1, "packets_dropped_filtered_by_kernel": 1226283, "meters_packets_processing_balance": [26339, 30357, 30336, 29309, 13793]}
{"flows_expired": 79864, "packets_processed": 137066, "packets_ignored": 1, "packets_dropped_filtered_by_kernel": 1430214, "meters_packets_processing_balance": [29126, 30357, 34481, 29309, 13793]}
{"flows_expired": 86927, "packets_processed": 146543, "packets_ignored": 2, "packets_dropped_filtered_by_kernel": 1591943, "meters_packets_processing_balance": [31033, 34479, 34481, 32757, 13793]}
{"flows_expired": 94164, "packets_processed": 146543, "packets_ignored": 2, "packets_dropped_filtered_by_kernel": 1591943, "meters_packets_processing_balance": [31033, 34479, 34481, 32757, 13793]}
{"flows_expired": 101827, "packets_processed": 148267, "packets_ignored": 2, "packets_dropped_filtered_by_kernel": 1643977, "meters_packets_processing_balance": [32757, 34479, 34481, 32757, 13793]}
{"flows_expired": 109951, "packets_processed": 155361, "packets_ignored": 2, "packets_dropped_filtered_by_kernel": 1871315, "meters_packets_processing_balance": [34679, 34479, 36205, 36205, 13793]}

and seems worse.
(155361-59017)/19=0.005Mpps

**Comment by aouinizied** [comment]
@missyoyo can you Edit your logs adding NFStream options?

**Comment by aouinizied** [comment]
@missyoyo  if this is your log with a single flow, it means that your active timeout is still at 1s.
total packets processed by nfstream = 3537360 + 12

```json
{"flows_expired": 1, "packets_processed": 147375, "packets_ignored": 8, "packets_dropped_filtered_by_kernel": 6998, "meters_packets_processing_balance": [0, 0, 147375, 0, 0]}
{"flows_expired": 2, "packets_processed": 296291, "packets_ignored": 9, "packets_dropped_filtered_by_kernel": 9906, "meters_packets_processing_balance": [0, 0, 296291, 0, 0]}
{"flows_expired": 3, "packets_processed": 449904, "packets_ignored": 9, "packets_dropped_filtered_by_kernel": 9906, "meters_packets_processing_balance": [0, 0, 449904, 0, 0]}
{"flows_expired": 4, "packets_processed": 603121, "packets_ignored": 9, "packets_dropped_filtered_by_kernel": 9906, "meters_packets_processing_balance": [0, 0, 603121, 0, 0]}
{"flows_expired": 5, "packets_processed": 756788, "packets_ignored": 9, "packets_dropped_filtered_by_kernel": 9906, "meters_packets_processing_balance": [0, 0, 756788, 0, 0]}
{"flows_expired": 6, "packets_processed": 910234, "packets_ignored": 9, "packets_dropped_filtered_by_kernel": 9906, "meters_packets_processing_balance": [0, 0, 910234, 0, 0]}
{"flows_expired": 7, "packets_processed": 1064904, "packets_ignored": 9, "packets_dropped_filtered_by_kernel": 9906, "meters_packets_processing_balance": [0, 0, 1064904, 0, 0]}
{"flows_expired": 8, "packets_processed": 1219811, "packets_ignored": 9, "packets_dropped_filtered_by_kernel": 9906, "meters_packets_processing_balance": [0, 0, 1219811, 0, 0]}
{"flows_expired": 9, "packets_processed": 1374707, "packets_ignored": 9, "packets_dropped_filtered_by_kernel": 9906, "meters_packets_processing_balance": [0, 0, 1374707, 0, 0]}
{"flows_expired": 10, "packets_processed": 1529096, "packets_ignored": 9, "packets_dropped_filtered_by_kernel": 9906, "meters_packets_processing_balance": [0, 0, 1529096, 0, 0]}
{"flows_expired": 11, "packets_processed": 1683681, "packets_ignored": 10, "packets_dropped_filtered_by_kernel": 9906, "meters_packets_processing_balance": [0, 0, 1683681, 0, 0]}
{"flows_expired": 12, "packets_processed": 1838232, "packets_ignored": 10, "packets_dropped_filtered_by_kernel": 9906, "meters_packets_processing_balance": [0, 0, 1838232, 0, 0]}
{"flows_expired": 13, "packets_processed": 1992949, "packets_ignored": 11, "packets_dropped_filtered_by_kernel": 9906, "meters_packets_processing_balance": [0, 0, 1992949, 0, 0]}
{"flows_expired": 14, "packets_processed": 2147330, "packets_ignored": 11, "packets_dropped_filtered_by_kernel": 9906, "meters_packets_processing_balance": [0, 0, 2147330, 0, 0]}
{"flows_expired": 15, "packets_processed": 2301594, "packets_ignored": 11, "packets_dropped_filtered_by_kernel": 9906, "meters_packets_processing_balance": [0, 0, 2301594, 0, 0]}
{"flows_expired": 16, "packets_processed": 2455956, "packets_ignored": 11, "packets_dropped_filtered_by_kernel": 9906, "meters_packets_processing_balance": [0, 0, 2455956, 0, 0]}
{"flows_expired": 17, "packets_processed": 2610496, "packets_ignored": 11, "packets_dropped_filtered_by_kernel": 9906, "meters_packets_processing_balance": [0, 0, 2610496, 0, 0]}
{"flows_expired": 18, "packets_processed": 2764923, "packets_ignored": 11, "packets_dropped_filtered_by_kernel": 9906, "meters_packets_processing_balance": [0, 0, 2764923, 0, 0]}
{"flows_expired": 19, "packets_processed": 2919370, "packets_ignored": 12, "packets_dropped_filtered_by_kernel": 9906, "meters_packets_processing_balance": [0, 0, 2919370, 0, 0]}
{"flows_expired": 20, "packets_processed": 3073885, "packets_ignored": 12, "packets_dropped_filtered_by_kernel": 9906, "meters_packets_processing_balance": [0, 0, 3073885, 0, 0]}
{"flows_expired": 21, "packets_processed": 3228619, "packets_ignored": 12, "packets_dropped_filtered_by_kernel": 9906, "meters_packets_processing_balance": [0, 0, 3228619, 0, 0]}
{"flows_expired": 22, "packets_processed": 3382814, "packets_ignored": 12, "packets_dropped_filtered_by_kernel": 9906, "meters_packets_processing_balance": [0, 0, 3382814, 0, 0]}
{"flows_expired": 23, "packets_processed": 3537360, "packets_ignored": 12, "packets_dropped_filtered_by_kernel": 9906, "meters_packets_processing_balance": [0, 0, 3537360, 0, 0]}
```

**Comment by missyoyo** [comment]
@aouinizied 
yes, I have change to 1s that is esay for calculation，I will change to default and test agin soon
![图片](https://user-images.githubusercontent.com/19371588/96096121-1022cf00-0f02-11eb-99bd-f8679a60013a.png)

**Comment by aouinizied** [comment]
To be able to help you we must fix these parameters to default ones as I said, and we will change one thing at each step. In other cases, it will be hard to figure out what is not working in your scenario.

**Comment by missyoyo** [comment]
@aouinizied 
I have another test with default interval with single flow, I have run test 12minute in total.
{"flows_expired": 0, "packets_processed": 92027830, "packets_ignored": 0, "packets_dropped_filtered_by_kernel": 3926, "meters_packets_processing_balance": [1, 0, 92027829, 0, 0]}
{"flows_expired": 0, "packets_processed": 92167553, "packets_ignored": 0, "packets_dropped_filtered_by_kernel": 3926, "meters_packets_processing_balance": [1, 0, 92167552, 0, 0]}
{"flows_expired": 0, "packets_processed": 92307260, "packets_ignored": 0, "packets_dropped_filtered_by_kernel": 3926, "meters_packets_processing_balance": [1, 0, 92307259, 0, 0]}
{"flows_expired": 0, "packets_processed": 92446963, "packets_ignored": 0, "packets_dropped_filtered_by_kernel": 3926, "meters_packets_processing_balance": [1, 0, 92446962, 0, 0]}
![图片](https://user-images.githubusercontent.com/19371588/96098330-93ddbb00-0f04-11eb-8821-a3c56604b848.png)
I got :
92446963/(12*60)/1000000=0.128Mpps

**Comment by aouinizied** [comment]
@missyoyo I see 0 drops. Do you confirm?

**Comment by missyoyo** [comment]
@aouinizied 
nfstream report no packet lost,Maybe I do not think so. I send packet rate 0.14 Mpps, Let me raise packet rate to 3Mpps, Maybe nfstream still report no packet lost.

**Comment by missyoyo** [comment]
@aouinizied 
![图片](https://user-images.githubusercontent.com/19371588/96099785-36e30480-0f06-11eb-9573-07de9d94be78.png)

**Comment by aouinizied** [comment]
@missyoyo at 3Mpps which MPPS you got from perf logs?

**Comment by missyoyo** [comment]
@aouinizied 
I got:
(1994900-144256)/14/1000000=0.132Mpps
![图片](https://user-images.githubusercontent.com/19371588/96100371-e28c5480-0f06-11eb-8492-55b1ad0df2d0.png)

**Comment by aouinizied** [comment]
@missyoyo nfstream do not compute drops, it reports only kernel drops as reported by libpcap. We are interested in these drops because they happen when app side does not read the buffer fast enough. 
In your case, you have 0 drops which means that nfstream is reading kernel buffers without lost. However, did you checked that your interface is not dropping packets??

**Comment by aouinizied** [comment]
@missyoyo once again please follow my recommendation when you are reporting your logs (markdown highlighting of JSON instead of screenshots)

**Comment by missyoyo** [comment]
@aouinizied 
Thank you for your explain,I do not thin raw libpcap can support 3Mpps,and NIC seems no packet lost
![图片](https://user-images.githubusercontent.com/19371588/96101638-42cfc600-0f08-11eb-91cb-be99aac6639e.png)
I have 3Mpps random flow test for nfstream, This time I got:
(729685-56353)/17/1000000=0.039Mpps,That is the best result for random flow.(default interval)
![图片](https://user-images.githubusercontent.com/19371588/96101359-f2f0ff00-0f07-11eb-90c4-ef5e4e98ce7f.png)

**Comment by aouinizied** [comment]
@missyoyo 
 we are using libpcap with fanout AFPACKETv3 support. And what is weird is that your reported results do not cope with what we usually achieve even on a smaller machine than yours.
Instead of random flows, Can you generate 5 continuous flows and make sure each flow will hit a meter. For example, increment src_port of each generated flow?

**Comment by missyoyo** [comment]
@aouinizied 
My packet genertator is test only. each flow is one way UDP small packet length(64bit min)
Thank you, Maybe I can try that. And it Maybe take some time. will update you later
I laso will use enterprise traffic in the futrue.  the result should more significant.
Thank you again.

**Comment by aouinizied** [comment]
@missyoyo OK.
Keep in mind these things to help you understand how things works:
* The load balancing (fanout) is done on the Linux kernel side.
*  If your traffic is well distributed: Each meter will handle total_load/n 
*  That's how nfstream scale horizontally depending on available cores/cpus.
*  If you want to test correctly how many PPS only, generate n flows and each flow has total_load/n pps.
*  Make sure that your test duration is realistic (not a few seconds) and start nfstream and stop it during test load to avoid performance report lines during no-load which will bias your results.


Make sure to keep default nfstream values, even for snapshot_length.

In the above scenario, you focus only on PPS, however, we can extend the benchmark with how many flows creation/s, flows expiration/s, etc.

Now, if you want to put things in their context here some calculations:
* On regular traffic average packet size is 1000, at this size the following statements are True.
* 0.1Mpps is equivalent to 0.7 Gbps
* 1 Mpps is equivalent to 7.4 Gbps
* 3 Mpps is equivalent to 22.3 Gbps

Will close this issue. Reopen it when you have more information.

**Comment by missyoyo** [comment]
Hello,it is me again, I have more test and I thinky may libpcap slow down nfstream.
I have one VM with 24vCPU installed(12*2),RAM 28GB,with X520 VF interface.I think nfstream can use 11 core to procced. So I use 11 flows for test.
I have write a simple program can dump RAW packet to RAM disk with 20s interval and let nfstream to procced these packet file.My dump program is base on DPDK. so can support high MPPS.
I have test 0.6Mpps，0.5Mpps ,0.4Mpps,0.3Mpps for file input for nfstream
My RAM disk has 14GB cached,if Nfstream can not procced these packet will cause RAM disk full.each test run 15min.
I have below test result:
0.6Mpps packet lost:(539515746-500,216,292)/539515746*100=7.28%,with RAM Disk full,fail
0.5Mpps packet lost:(450149994-450,020,975)/450149994*100=0.02%,RAM disk not full.But has 7.9GB file need procced after packet sender stoped.so also fail
0.4Mpps packet lost:(359052687-359,049,526)/359052687*100=0.0008%,with 1.9GB file after packet sender stoped.I below this test has no packet lost,Because my dump programe always get less packet than packet sender.test pass
0.3Mpps packet lost:(269699850-269,690,126)/269699850*100=0.03%,with 400MB file after packet sender stoped.test pass.

So I have test nfstream for nic live packet capture,with the same config,(11 core works)
0.3Mpps packet lost:(269701173-250018573)/269701173*100=7.2%
0.2Mpps packet lost:(178675308-166959123)/178675308*100=6.5%
0.12Mpps packet lost:(107536275-107515263)/107536275*100=0.019% OR
(107536275-107515263-31)/107536275*100=0.019%
I think 0.12Mpps nfstream live capture no packet lost.
{"flows_expired": 1007, "packets_processed": 107515263, "packets_ignored": 31, "packets_dropped_filtered_by_kernel": 0, "meters_packets_processing_balance": [42, 0, 64, 17919175, 17919182, 26878746, 17919184, 8959702, 0, 8959578, 8959590]}

So I believe libpcap can not send packet fast enough to nfstream, would you like to consider add faster packet capture support to nfstream(DPDK for example),Thank you.

**Comment by aouinizied** [comment]
@missyoyo 
Please upgrade to the last version as I changed how autoscale works.
Here some points you are missing with your scenario:

* When you are using DPDK to dump file and nfstream to read from file. NFStream will scale in an offline mode. This means that it will start n consumers but each consumer will read all packets and process only packets that are matching the consumer id (based on a flow hash). So basically, we [simulate](https://github.com/nfstream/nfstream/blob/4777b93f8b4d63162f707a82f51ed22d15499805/nfstream/context_cc.c#L498) fanout and each packet is still parsed by all consumers.
* In live mode, nfstream load balancing (hash and assign to a consumer) is done in the [kernel](https://github.com/torvalds/linux/blob/9ff9b0d392ea08090cd1780fb196f36dbb586529/net/core/flow_dissector.c#L1578) and consequently each consumer will process and parse only packets assigned to it.

So to sum up, if you have 1000 packets and 10 consumers and let's suppose that the flow hashing function assigns 100 packets per consumer (perfect distribution):

* In offline mode: each consumer will see 1000 packets, parse them, and based on flow hash, will process 100 packets.
* In online mode: each consumer will see only 100 packets and process them. 

So NFStream performance on Linux, Live mode is not comparable to offline mode. And Live mode on Linux will always be much more efficient.

Now let's focus on your performance results in Live mode

* From what I'm seeing there are at least 4 meters that are received only a few packets, so there is obviously an issue with how you configured your 11 flows.
* NFStreamer options are missing so I cannot help you without it.

Please upgrade your version and restart live tests and make sure you generate n well-distributed flows. You will see that the new version enables all CPUs instead of cores so you will probably need to generate more flows.

Once it's done, make sure you use proper [syntax highlighting](https://stackoverflow.com/questions/14901245/how-to-style-a-json-block-in-github-wiki) when you report JSON (FULL performance report) or Python (NFStreamer code) in order to make it readable for us and we will be able to help you.

**Comment by missyoyo** [comment]
@aouinizied 
Thank you for your explaination,I have optimize my program and I have run 1Mpps with file input now with out issue now(TX: 1.00Mpps, 705 Mbit/s , total 1801306017 packets), and packet lost:(1801306017-1,801,288,062)/1801306017=0.00099%.
it can be more higher MPPS, when I get more RAM chache and CPU core.
I have not try 6.2.0 jet.
I will update if I get better results
