### ISSUE TITLE
When read source from pcap file, `lib.capture_next()` was blocked.

### ISSUE THREAD

**Issue by zu1k** [nfstream/nfstream#39]
**Describe the bug**

When I traverse all the flows, It never end, and print("END") never be execed.
The source is a botnet dataset, is a pcap file.

```python3
my_streamer = NFStreamer(source="ISCX_Botnet-Testing.pcap",  # or network interface
                         decode_tunnels=True,
                         bpf_filter=None,
                         promiscuous_mode=True,
                         snapshot_length=1536,
                         idle_timeout=15,
                         active_timeout=120,
                         accounting_mode=0,
                         udps=FlowSlicer(),
                         n_dissections=20,
                         statistical_analysis=True,
                         splt_analysis=28,
                         n_meters=0,
                         performance_report=0)

for flow in my_streamer:
    print(flow)

print("END")  # END will not be printed
```

I debug it, found that `lib.capture_next()` was blocked, would never return.
https://github.com/nfstream/nfstream/blob/master/nfstream/meter.py#L212

**Expected behavior**
Stop when all the flows was closed, or timeout.

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Python version 3.8

**Additional context**
pcap file was downloaded from [https://www.unb.ca/cic/datasets/botnet.html](https://www.unb.ca/cic/datasets/botnet.html)

**Comment by aouinizied** [comment]
@zu1k Thanks for your report.
It is possible to provide us with the version of NFStream you are using in order to reproduce.

Zied

**Comment by zu1k** [comment]
> @zu1k Thanks for your report.
> It is possible to provide us with the version of NFStream you are using in order to reproduce.
> 
> Zied

Thanks for your reply.
I use the latest release whose version is 6.2.0

**Comment by aouinizied** [comment]
@zu1k I cannot reproduce your bug. Can you try the following code, please?
In my case, it ends without issue and print 188976 using the same pcap you provided.

```python
from nfstream import NFStreamer

my_streamer = NFStreamer(source="ISCX_Botnet-Testing.pcap",  # or network interface
                         decode_tunnels=True,
                         bpf_filter=None,
                         promiscuous_mode=True,
                         snapshot_length=1536,
                         idle_timeout=15,
                         active_timeout=120,
                         accounting_mode=0,
                         n_dissections=20,
                         statistical_analysis=True,
                         splt_analysis=28,
                         n_meters=0,
                         performance_report=0)


total_flows = 0
for flow in my_streamer:
    total_flows += 1
print(total_flows)
```

**Comment by zu1k** [comment]
Thanks for your work, I found it's my fault, now problem was solved.

The problem is `udps=FlowSlicer()` here, the internal processing is blocked.
