### ISSUE TITLE
Need more examples about online capture

### ISSUE THREAD

**Issue by daoxuans** [nfstream/nfstream#40]
Hi, can you provide more examples about online capture?
1. How to export to csv or pandas when live capture?
2. How to shutdown the online capture task gracefully？
Thank you.

**Comment by drnpkr** [comment]
Hey there!

Sure thing. Did you try looking at this example?

https://github.com/nfstream/nfstream/blob/master/examples/csv_generator.py

1. It does export to CSV. 
2. You just hit CTRL+C. NFStream will take of the rest.

**Comment by daoxuans** [comment]
> Hey there!
> 
> Sure thing. Did you try looking at this example?
> 
> https://github.com/nfstream/nfstream/blob/master/examples/csv_generator.py
> 
> 1. It does export to CSV.
> 2. You just hit CTRL+C. NFStream will take of the rest.

Thanks, i test it in my testbed, two examples passed.
My test case failed when i try export live capture results to pandas, i am not familiar with pandas. this is my code:
`[root@NJNAC examples]# cat csv_generator.py
"""
------------------------------------------------------------------------------------------------------------------------
csv_generator.py
Copyright (C) 2019-20 - NFStream Developers
This file is part of NFStream, a Flexible Network Data Analysis Framework (https://www.nfstream.org/).
NFStream is free software: you can redistribute it and/or modify it under the terms of the GNU Lesser General Public
License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later
version.
NFStream is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty
of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU Lesser General Public License for more details.
You should have received a copy of the GNU Lesser General Public License along with NFStream.
If not, see <http://www.gnu.org/licenses/>.
------------------------------------------------------------------------------------------------------------------------
"""

from nfstream import NFStreamer
import sys

path = sys.argv[1]
print("nfstream processing started. Use Ctrl+C to interrupt and save.")
total_flows = NFStreamer(source=path,
                         statistical_analysis=True,
                         splt_analysis=10,
                         performance_report=1).to_pandas()[["src_ip",
                                                            "src_port",
                                                            "dst_ip",
                                                            "dst_port",
                                                            "protocol",
                                                            "bidirectional_packets",
                                                            "bidirectional_bytes",
                                                            "application_name"]]
`
my testbed log is:
`[root@NJNAC examples]# python3 ./csv_generator.py  ha
nfstream processing started. Use Ctrl+C to interrupt and save.
{"flows_expired": 0, "packets_processed": 0, "packets_ignored": 0, "packets_dropped_filtered_by_kernel": 0, "meters_packets_processing_balance": [0, 0, 0]}
{"flows_expired": 0, "packets_processed": 3, "packets_ignored": 0, "packets_dropped_filtered_by_kernel": 0, "meters_packets_processing_balance": [1, 1, 1]}
{"flows_expired": 0, "packets_processed": 385, "packets_ignored": 10, "packets_dropped_filtered_by_kernel": 0, "meters_packets_processing_balance": [344, 34, 7]}
^CTraceback (most recent call last):
  File "./csv_generator.py", line 24, in <module>
    performance_report=1).to_pandas()[["src_ip",
  File "/usr/local/lib/python3.6/site-packages/nfstream/streamer.py", line 360, in to_pandas
    df = pd.read_csv(temp_file_path)
  File "/usr/local/lib64/python3.6/site-packages/pandas/io/parsers.py", line 688, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/usr/local/lib64/python3.6/site-packages/pandas/io/parsers.py", line 454, in _read
    parser = TextFileReader(fp_or_buf, **kwds)
  File "/usr/local/lib64/python3.6/site-packages/pandas/io/parsers.py", line 948, in __init__
    self._make_engine(self.engine)
  File "/usr/local/lib64/python3.6/site-packages/pandas/io/parsers.py", line 1180, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "/usr/local/lib64/python3.6/site-packages/pandas/io/parsers.py", line 2010, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas/_libs/parsers.pyx", line 382, in pandas._libs.parsers.TextReader.__cinit__
  File "pandas/_libs/parsers.pyx", line 674, in pandas._libs.parsers.TextReader._setup_parser_source
FileNotFoundError: [Errno 2] No such file or directory: 'nfstream-2813-1-1605111399.626871?csv'
`

**Comment by drnpkr** [comment]
What are you passing in ha?

Also, in the output, you see 0 flows expired. This means that no expiration time has expired since the start of the live packet capture (flow generation). Therefore, you have 0 flows in total_flows.

**Comment by daoxuans** [comment]
1. 'ha' is my eth interface.  
![ha](https://user-images.githubusercontent.com/6179315/98788924-800e7180-243c-11eb-8575-f0b863b5780c.PNG)

2. Thank you for your reminder, i have to stop after the session timeout statistics.
![correct](https://user-images.githubusercontent.com/6179315/98789276-0c209900-243d-11eb-99c6-ab300cac476b.PNG)

3. The last question is ‘Session ends only because of timeout’, cannot correctly handle similar TCP FIN packets.
Is this due to nDPI?

**Comment by drnpkr** [comment]
I do not entirely understand your question.

TCP FIN/RST flag is handled correctly in NFStream. If there is one such a packet, it will be recorded. If there are no more packets observed in the flow after a FIN or RST, the timeout will expire the flow and it will be removed from the flow cache. 

In TCP, normally you would have an internal timer for session termination. We do not implement such an internal timer. 

Why? Because all the observed packets up to the expiration will be recorded correctly. The flow duration will be also correct as the last packet in the flow will be the end timestamp of the flow, right? So the only flaw of NFStream is that it keeps the flow a bit longer in the cache that is supposed to. But the metrics will be accurate, tho.

In what context you wrote similar TCP FIN packets? In a flow, you would see max 2 FINs (if measuring in both directions). If you see only one and the flow is expired, you can consider the other FIN being lost (NFStream did not record it for some reason out of its control).

I hope the above mentioned clarifies your questions.

**Comment by daoxuans** [comment]
1. From the perspective of reducing overhead, the session can be released immediately after FIN. however, using unified timeout detection mechanism  can simplify processing. so i agree with this solution.
2. There are two parameter explanations that need to be checked.
  ![limit](https://user-images.githubusercontent.com/6179315/98793931-7a685a00-2443-11eb-94d2-e2af71a80672.PNG)
- This is used to limit resource consumption per session, right?
  ![min](https://user-images.githubusercontent.com/6179315/98794322-df23b480-2443-11eb-82fe-546414bb19a9.PNG)
- can you give me more details about this? eg. `n_dissections = 100` What it means?

**Comment by drnpkr** [comment]
In my interpretation active timeout is primarily for providing near real-time measurement. If a flow duration is half an hour, the measurement data would be analysed after this flow has expired by passive timeout. To make things timely, there is an active timeout. So despite there are still packets observed for the flow, its data will be expired and exported for analysis (visualisation, etc.).

n_dissection - well, it is written there, the number of packets of the flow used for labelling the flow (L7).

**Comment by daoxuans** [comment]
Thanks for your explanation
