### ISSUE TITLE
BPF filter works only in file capture mode

### ISSUE THREAD

**Issue by adamjanovsky** [nfstream/nfstream#42]
Hi,

I'm not certain whether this is a desired behaviour or not, but at the moment my attempts to provide BPF filter (according to syntax at https://biot.com/capstats/bpf.html) for live capture have failed with error `ERROR: Unable to compile BPF filter.`

When run on a file, the filter behaves correctly. See the following working example:

```
bpf_filter="src port 52066 or dst port 52066"
streamer = NFStreamer(source='./path/to/something.pcap', bpf_filter=bpf_filter)
total_flows_count = streamer.to_csv(path='./flows/test.csv', columns_to_anonymize=[])
```

Reproducing an issue can be done simply by changing the `source` attribute to a live interface. This bug concerns Ubuntu 18.04 and nfstream=6.2.2.

If the bpf filter is not meant to be working with live capture, can you please add it to documentation? In such case, how can I filter traffic when doing live capture? Can I e.g. delete specific flows from streamer on expiry? Didn't quite understand the access to the internal storage of flows.

**Comment by aouinizied** [comment]
Hi Adam,

Thanks for your report. BPF filtering must work on both live and offline features.
I fixed the issue you encountered on live capture, will be released within v6.2.3.

If you need some help on NFPlugins part, do not hesitate to fill a new issue and we can help you based on your use case.

Zied

**Comment by aouinizied** [comment]
@adamjanovsky upgrade to v6.2.3 and your issue will be fixed. Do you confirm?
```shell
pip install --upgrade nfstream
```

**Comment by adamjanovsky** [comment]
works like a charm, thanks a lot for resolving! Feel free to close.
