### ISSUE TITLE
to_csv() function does not accept Path object, only str

### ISSUE THREAD

**Issue by adamjanovsky** [nfstream/nfstream#43]
**Describe the bug**

As of version 6.2.3, the `NFStream` function `to_csv()` accepts path as the input attribute. Unfortunately, a string type must be passed for the function to properly work. I would expect the that the function will be able to work with the type `Path` from pathlib or os modules. 

**To Reproduce**

1. Start capture
2. Attempt to save the results into csv. See snippet below:

```
from pathlib import Path
from nfstream import NFStreamer

csv_path = Path('path/to/your/csv/file') # Make sure to create /path/to/your/csv prior to running
streamer = NFStreamer(source='name_of_live_interface', statistical_analysis=True)
streamer.to_csv(csv_path, flows_per_file=10)
```

**Expected behavior**
I would expect the function `to_csv()` accept Path object.

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.0.4
 - Python version: 3.8
 - NFStream version: 6.2.3

**Additional context**
Naturally, easy fix is to call `str(your_path_object)`. From this perspective, this is rather minor bug. More of a improvement suggestion.

**Comment by tirkarthi** [comment]
Using `os.fspath` is a better option : https://docs.python.org/3/library/os.html#os.fspath

**Comment by aouinizied** [comment]
Fixed in https://github.com/nfstream/nfstream/commit/f61f5e1885aa2ffcce2f18bd74da069952a318da bu switching to fspath.

Zied
