### ISSUE TITLE
to_csv() function broken when 0 flows in Streamer object

### ISSUE THREAD

**Issue by adamjanovsky** [nfstream/nfstream#44]
**Describe the bug**

The `NFStreamer` function `to_csv()` results into exception, when there are no flows in the streamer iterator. Consequently, this also breaks `to_pandas()` function. 

The issue is caused because the file is opened (and header crafter) only if the streamer has some flows to iterate over. See [streamer.py -- line 330](https://github.com/nfstream/nfstream/blob/master/nfstream/streamer.py#L330). 

**To Reproduce**
1. Start live capture on interface with `NFStreamer` instance and immediately stop it.
2. Call `to_csv()` function on your streamer instance. 
3. See the exception

**Expected behavior**
In case when no flows are in the streamer, the function should either produce no file or produce an empty file only with a header.

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Python version: 3.8
 - NFStream version: 6.2.3

Thanks a lot for resolving! Should be an easy fix.

**Comment by aouinizied** [comment]
Fixed in https://github.com/nfstream/nfstream/commit/f61f5e1885aa2ffcce2f18bd74da069952a318da.

If there are no flows, the file is not created.
If there are no flows, Dataframe is None.

Zied
