### ISSUE TITLE
query / feature request: open gzip and bz2 files directly

### ISSUE THREAD

**Issue by gjvc** [nfstream/nfstream#46]
Hello,

First of all, thank you for your efforts on this project -- it looks very promising indeed for my scenario, especially so with the compatibility with Pypy, which will really enable what I have in mind.

I have many thousands of .pcap files stored in BZIP2 format covering a few years (filenames being source-date.pcap.bz2, quite predictably :-))

I would like to be able to open them and parse them directly from within nfstream without having to decompress them first to temporary files, which really is a bit messy.

Depending on the implementation it might be more performant to use bzcat or gzcat and pipe the input into the process.

I'll happily have a go at adding support for recognising .gz and .bz2 filenames passed as source='/some/where/file/name' to various functions and create a pull request, but I wanted to ask first.

Thanks again :-)

**Comment by aouinizied** [comment]
@gjvc Hi George,

This is definitively a nice feature to have. Feel free to open a PR and we will be here if you need help.

Some points to keep in mind:
* Once implemented, make sure to add a test file and a test function in tests.py and CI will run the tests on Linux, Macos, arm with several Python versions.
* I guess your change will be on two sides: Streamer.py to allow such parameter format and engine.c  for decompression handling.

Some references that can help:
* https://github.com/raybellis/libpcap-gzip
* https://stackoverflow.com/questions/46320975/is-it-possible-to-parse-pcap-packets-from-buffer

Regards,
Zied

**Comment by aouinizied** [comment]
@gjvc Any update regarding this feature?

**Comment by aouinizied** [comment]
Closed for inactivity, Feel free to reopen it.
