### ISSUE TITLE
Throw exception when setup capture fails

### ISSUE THREAD

**Issue by SoerenBusse** [nfstream/nfstream#48]
**Describe the bug**
When running NFStreamer with a file of zero bytes, it obviously fails and prints an error in the console:
`ERROR: Unable to open source /tmp/9ed4597f-3308-4d79-9486-8efcbb6ef3d3_test9mb.pcap: truncated dump file; tried to read 4 file header bytes, only got 0`

However it doesn't throw an exception and silently fails. We're using NFStreamer in an automated, unattended setup for analyzing pcap files, so we cannot react on this type of error, if it doesn't throw an exception.

I think it's related to this code, where it's only returns nothing instead of throwing an exception:
https://github.com/nfstream/nfstream/blob/ca3df0bb2a7062d884e3e66ca4ac6f273554095d/nfstream/meter.py#L199

Is it possible to add an exception for this cases or is there an alternative, even better way to catch the errors of NFStreamer?

**To Reproduce**
```python
pcap_streamer = NFStreamer(source="zero_bytes.pcap)
       
for flow in pcap_streamer:
    # Do something with the flow
```

Will throw the mentioned error.

**Expected behavior**
It should throw an exception or any other python interpretable way of handling those errors.

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Python version: 3.8
 - NFStream version: 6.2.0

**Comment by aouinizied** [comment]
@SoerenBusse Thanks for reporting.
Indeed this must be changed for your use case and for all possible errors that happen in the child processes scope.
The child processes (meters) must communicate the error to the parent one (streamer) and exception must be thrown at the parent level. This will allow you to catch it and to perform whatever actions you want.
Will work on it and inform you when a patch is available.

Zied

**Comment by aouinizied** [comment]
@SoerenBusse Patch implemented. Now NFStreamer will raise ValueError exception for this use case. (included in next release)
