### ISSUE TITLE
bpf filter with not operand didn't work

### ISSUE THREAD

**Issue by yusuf81** [nfstream/nfstream#49]
**Describe the bug**
bpf filter does not work when using the not operand. either it use "!" or "not".

**To Reproduce**
df1 = NFStreamer(source="sample-20210129.pcap",bpf_filter="dst 10.23.2.1") --> this work
df1 = NFStreamer(source="sample-20210129.pcap",bpf_filter="! dst 10.23.2.1") --> this didn't work
df1 = NFStreamer(source="sample-20210129.pcap",bpf_filter="not dst 10.23.2.1") --> this didn't work

**Expected behavior**
not operand should work, because it's trivial bpf filter syntax

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10 WSL 2 (Ubuntu 20.04)
 - Python version [e.g. 3.8.5]
 - NFStream version 6.2.5

**Comment by aouinizied** [comment]
@yusuf81 Thanks for reporting, can you attach the pcap file used for your use case?

**Comment by aouinizied** [comment]
It's working on my case with the following code.

```python
from nfstream import NFStreamer

streamer_test_not = NFStreamer(source='tests/facebook.pcap', bpf_filter="not src port 52066")

for f in streamer_test_not:
    if f.src_port == 52066:
        print("Not operand not working")

streamer_test= NFStreamer(source='tests/facebook.pcap', bpf_filter="src port 52066")

for f in streamer_test:
    if f.src_port == 52066:
        print("Flow exists and match")
```
