### ISSUE TITLE
Big difference between flows generated via live capture vs pcap file 

### ISSUE THREAD

**Issue by sunny-r** [nfstream/nfstream#51]
Hello

I'm not sure why I'm seeing such a big difference in my results. I'm not using a bpf filter.

I kick off a tcpdump process to generate a pcap file off my ethernet interface:
`sudo /usr/sbin/tcpdump -i eno2 -nN -s0 -Z myusername -U -C 2048 -w capture.pcap`

At the same time, in a python interpreter shell instantiated with `sudo python3`, I run this:
`streamer = nfstream.NFStreamer(source="eno2",promiscuous_mode=True,statistical_analysis=True)`
`df = streamer.to_pandas()`

I end both processes at the same time. I then also created a dataframe from the pcap file
`streamer = nfstream.NFStreamer(source="capture.pcap",statistical_analysis=True,promiscuous_mode=True)`
`df = streamer.to_pandas()`

The number of rows was drastically different; running df.shape:

dataframe shape from live capture: (82, 84)
dataframe shape from pcap file: (838, 84)

I would have expected both dataframes to be very similar, indeed close to being identical. I can see websites I visited during the time period in the pcap-dataframe, but not the live-dataframe. My setup:

Desktop:
OS: Linux Mint 19.1 Tessa
Python 3.6.9
NFStream 6.2.5

I tried running another live capture, but this time with `snapshot_length=262144` which is apparently the same as passing option and argument `s0` to tcpdump (according to the man pages), but that made no difference in the number of flows generated.

I ran a live capture with `performance_report=1` as an argument to `NFStreamer`, there's nothing in there that gave me cause for alarm. Here's the final row before I ended the stream:
`{"flows_expired": 0, "packets_processed": 31294, "packets_ignored": 153, "packets_dropped_filtered_by_kernel": 0, "meters_packets_processing_balance": [421, 709, 7227, 1359, 7520, 597, 13461]}`

How can I find out what I'm doing wrong?

Thanks!

**Comment by drnpkr** [comment]
Hi @sunny-r,

I suspect your two competing processes try to access the same source that eventually results in an odd case where one of them simply cannot observe the packets (in simple words).

Packet capture without loss on high-speed links on commodity hardware is a critical task that could be affected by several factors such as another resource-demanding process. What is the throughput of the link you capture packets from?

**Comment by sunny-r** [comment]
Hi @drnpkr,

So I'm pretty sure this isn't a hardware issue - I still get this issue when only running nfstream-live. I only ran parallel captures to confirm that tcpdump/libpcap was seeing packets that nfstream wasn't.

I thought I'd also test out live captures on my mini PC, and my laptop - same issue.

I uninstalled nfstream and grabbed an old version:
`sudo pip3 install nfstream==6.0.0`

And this seems to have solved it - I suspect something broke between 6.0.0 and the latest release?

**Comment by sunny-r** [comment]
Hi @drnpkr 

I've been doing a bit more testing; I think nfstream live capture was fine at 6.0.5, but not at 6.1.0 onwards.

**Comment by drnpkr** [comment]
Hi @sunny-r 

This is behaviour is very strange. 

Could you please flick me an email so we can schedule a call to have a look at this in more detail?

**Comment by sunny-r** [comment]
Sure thing, what email address can I reach you on?

I'm not sure how helpful I'll be - I don't understand the inner workings of the nfstream-livecapture. I'm only specifying `source="eno2"` as my argument to `NFStream` and I still see the same behaviour.

Have you compared live capturing using an old version of nfstream with the newest? Have you been able to replicate this?

**Comment by drnpkr** [comment]
Hi @sunny-r,

sorry for the radio silence, my email is apekar[at]hit[dot]bme[dot]hu

**Comment by aouinizied** [comment]
@sunny-r This is normal behavior (implementation choice). I will try to explain how things work:
* Offline Mode: This is the case when you start NFStream on the pcap generated by tcpdump. 
* Online Mode: This the live capture use case.

The difference you see is due to the fact that when there is a Keyboard interrupt and you are in live mode, NFStream shutdown without flushing the flows that are remaining in the cache. These flows are active at the time you press Ctrl+C but they are not expired yet (active, idle timeouts).

In offline mode, NFStream detects the end of the pcap file and considers the remaining flows in the cache as inactive, and exports them before shutdown.

If you reduce your idle timeout, you will see that you will have less difference.

This is an implementation choice in order to not include flows that are not expired in Live. It must be specified in the documentation.

Regards,
Zied
