### ISSUE TITLE
Flow payload

### ISSUE THREAD

**Issue by mluethi** [nfstream/nfstream#53]
Hello!

I'm looking for a way to get the payload of the flow for further analysis.
By payload I mean all data except TCP/UDP headers.

I image something like:

`my_streamer = NFStreamer(source="facebook.pcap", ... export_flow_size=256, ...)`

`NFlow` should get a new attribute `flow_data: bytes` with the data (if `export_flow_size is > 0`) or `None` otherwise.

Thanks for your help!
Regards,
Marcel

**Comment by aouinizied** [comment]
Hi,

You can access the payload of each packet belonging to a flow within a Plugin. When your Plugin is called per flow, NFPacket has an attribute 'ip_packet' containing the payload and you can use it whatever you want to create a new flow attribute.

See the Plugins repository in order to have an idea of how to write a Plugin.

Zied

**Comment by mluethi** [comment]
Great! Thanks for the answer!

So that means I get the payload like this: `packet.ip_packet[-packet.payload_size:]` in a NFPlugin?
**That works!** But of course only for one-packet flows...

If the flow is consists of more than one packet, I would have to do something like this?

```
class PayloadCollector(NFPlugin):

    def on_init(self, packet, flow):
        flow.udps.my_payload = bytearray()

    def on_update(self, packet, flow):
        if packet.payload_size > 0:
            payload = packet.ip_packet[-packet.payload_size:]
            flow.udps.my_payload.extend(payload)


stream = NFStreamer(source=pcap_file, statistical_analysis=False, udps=PayloadCollector())
for flow in stream:
    print(f'{flow.id} => {flow.udps.my_payload}')
```

Correct?
I don't have to do anything in `on_expire`?

Thanks a lot for your help!
I'm already looking a long time to find an answer...

Regards -.- Marcel

**Comment by aouinizied** [comment]
@mluethi you are missing the first packet if it contains a payload. Do not forget that on_init is called with the first packet and on_update is called for the rest of the packets belonging to the flow. In your use case, no need for an on_expire indeed.

```python
from nfstream import NFStreamer, NFPlugin

class PayloadCollector(NFPlugin):

    @staticmethod
    def _extend_flow_payload(packet, flow):
        if packet.payload_size > 0:
            payload = packet.ip_packet[-packet.payload_size:]
            flow.udps.my_payload.extend(payload)

    def on_init(self, packet, flow):
        flow.udps.my_payload = bytearray()
        self._extend_flow_payload(packet, flow)

    def on_update(self, packet, flow):
        self._extend_flow_payload(packet, flow)


stream = NFStreamer(source="tests/facebook.pcap", statistical_analysis=False, udps=PayloadCollector())
for flow in stream:
    print(f'{flow.id} => {flow.udps.my_payload}')
```
