### ISSUE TITLE
ValueError: cannot find context for 'fork'

### ISSUE THREAD

**Issue by Haris1904** [nfstream/nfstream#55]
**Describe the bug**
ValueError: cannot find context for 'fork'

**To Reproduce**
1. Install NFStream
2. Download Dataset
3. Run given code 

**Expected behavior**
Expected a CSV file with flows  

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - Python version 3.8
 - NFStream version 6.2.5
![Screenshot (37)](https://user-images.githubusercontent.com/51179305/109923476-aa808500-7ce0-11eb-9532-9967efa99b4f.png)

**Additional context**

**Comment by drnpkr** [comment]
Hi @Haris1904,

NFStream is currently supported on major Linux distributions, macOS and ARM (64bits) based platforms. While you might be able to install NFStream in Python (as I document in your bug issue), it depends on libraries that might not be supported in Windows.

**Comment by aouinizied** [comment]
@Haris1904 NFStream is supported and tested on Linux and macOS. Windows support in a long-term plan. Do not hesitate to contribute if you use Windows platform (Mainly compiling the engine of NFStream which is C based and its dependencies).

Regards,
Zied
