### ISSUE TITLE
Cannot run from source, function name changed in nDPI, `ndpi_finalize_initalization` not found

### ISSUE THREAD

**Issue by neyney10** [nfstream/nfstream#56]
## Bug Description
Cannot longer run from sources (although it does compile) because of the function `ndpi_finalize_initalization` is missing.
Which is used in `engine_cc.c` in function `dissector_configure`.

## Reason for the problem
There was a typo in the function name and it got changed around 10 days ago in nDPI.
see: https://github.com/ntop/nDPI/commit/fc3db8f1691e913b03ca88a47770c5abf3104ef8

From:
```
ndpi_finalize_initalization(ndpi_str);
```
To:
```
ndpi_finalize_initialization(ndpi_str);
```

('i' character is added in 'initialization')

## To Reproduce
1. Install from sources according the guide.
2. When creating the .so file (shared object) of engine_cc, in compilation it notes that:
```
engine_cc.c:1944:7: warning: implicit declaration of function ‘ndpi_finalize_initalization’; did you mean ‘ndpi_finalize_initialization’? [-Wimplicit-function-declaration]
       ndpi_finalize_initalization(dissector);
       ^~~~~~~~~~~~~~~~~~~~~~~~~~~
       ndpi_finalize_initialization
```
2. Try to run a simple script in python. that uses NFStream.
3. Error: In file `engine.py` in function `create_engine` while trying to open shared library with dlopen.
4. The error says:
```
Process Process-1:
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "<censored-path>/meter.py", line 201, in meter_workflow
    ffi, lib = create_engine()
  File "<censored-path>/engine.py", line 1215, in create_engine
    lib = ffi.dlopen(dirname(abspath(__file__)) + '/engine_cc.so')
  File "<censored-path>/.local/lib/python3.6/site-packages/cffi/api.py", line 150, in dlopen
    lib, function_cache = _make_ffi_library(self, name, flags)
  File "<censored-path>/.local/lib/python3.6/site-packages/cffi/api.py", line 832, in _make_ffi_library
    backendlib = _load_backend_lib(backend, libname, flags)
  File "<censored-path>/.local/lib/python3.6/site-packages/cffi/api.py", line 827, in _load_backend_lib
    raise OSError(msg)
OSError: cannot load library '<censored-path>/engine_cc.so': <censored-path>/engine_cc.so: undefined symbol: ndpi_finalize_initalization.  Additionally, ctypes.util.find_library() did not manage to locate a library called <censored-path>/engine_cc.so'
```
## Expected behavior
No problems in running or compilation.

## Desktop
 - OS: Ubuntu 18.04 WSL2 on Windows 10
 - Python version: 3.69
 - NFStream version. latest, 6.25

**Comment by aouinizied** [comment]
@neyney10 Thanks for reporting. It was due to both this API change + several updates in nDPI structures. Fixed in https://github.com/nfstream/nfstream/commit/3c64e0ff55e0f3f0742bfee082eee37dcbd4c871

Zied
