### ISSUE TITLE
Tests fail empty suite

### ISSUE THREAD

**Issue by 01abdullah** [nfstream/nfstream#57]
"C:\Program Files\python.exe" "C:\Program Files\JetBrains\PyCharm Community Edition 2020.2.1\plugins\python-ce\helpers\pycharm\_jb_unittest_runner.py" --path "C:/Users/SRGW7506/Desktop/Masters/Project code/nfstream-master/tests.py"
Testing started at 16:30 ...
Launching unittests with arguments python -m unittest C:/Users/SRGW7506/Desktop/Masters/Project code/nfstream-master/tests.py in C:\Users\SRGW7506\Desktop\Masters\Project code\nfstream-master

Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2020.2.1\plugins\python-ce\helpers\pycharm\_jb_unittest_runner.py", line 35, in <module>
    sys.exit(main(argv=args, module=None, testRunner=unittestpy.TeamcityTestRunner, buffer=not JB_DISABLE_BUFFERING))
  File "C:\Program Files\lib\unittest\main.py", line 100, in __init__
    self.parseArgs(argv)
  File "C:\Program Files\lib\unittest\main.py", line 147, in parseArgs
    self.createTests()
  File "C:\Program Files\lib\unittest\main.py", line 158, in createTests
    self.test = self.testLoader.loadTestsFromNames(self.testNames,
  File "C:\Program Files\lib\unittest\loader.py", line 220, in loadTestsFromNames
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "C:\Program Files\lib\unittest\loader.py", line 220, in <listcomp>
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "C:\Program Files\lib\unittest\loader.py", line 154, in loadTestsFromName
    module = __import__(module_name)
  File "C:\Users\SRGW7506\Desktop\Masters\Project code\nfstream-master\tests.py", line 22, in <module>
    from nfstream import NFStreamer
  File "C:\Users\SRGW7506\Desktop\Masters\Project code\nfstream-master\nfstream\__init__.py", line 17, in <module>
    from .streamer import NFStreamer
  File "C:\Users\SRGW7506\Desktop\Masters\Project code\nfstream-master\nfstream\streamer.py", line 31, in <module>
    mp.set_start_method("fork")
  File "C:\Program Files\lib\multiprocessing\context.py", line 247, in set_start_method
    self._actual_context = self.get_context(method)
  File "C:\Program Files\lib\multiprocessing\context.py", line 239, in get_context
    return super().get_context(method)
  File "C:\Program Files\lib\multiprocessing\context.py", line 193, in get_context
    raise ValueError('cannot find context for %r' % method) from None
ValueError: cannot find context for 'fork'

Process finished with exit code 1

Empty suite

**Comment by 01abdullah** [comment]
I'm sorry as I'm new to this but I have installed ubuntu and setup all packages and modules but BPFilter test fails

Process Process-1:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/abdullah/Downloads/nfstream-master/nfstream/meter.py", line 197, in meter_workflow
    ffi, lib = create_engine()
  File "/home/abdullah/Downloads/nfstream-master/nfstream/engine/engine.py", line 1218, in create_engine
    lib = ffi.dlopen(dirname(abspath(__file__)) + '/engine_cc.so')
  File "/home/abdullah/Downloads/nfstream-master/venv/lib/python3.8/site-packages/cffi/api.py", line 150, in dlopen
    lib, function_cache = _make_ffi_library(self, name, flags)
  File "/home/abdullah/Downloads/nfstream-master/venv/lib/python3.8/site-packages/cffi/api.py", line 832, in _make_ffi_library
    backendlib = _load_backend_lib(backend, libname, flags)
  File "/home/abdullah/Downloads/nfstream-master/venv/lib/python3.8/site-packages/cffi/api.py", line 827, in _load_backend_lib
    raise OSError(msg)
OSError: cannot load library '/home/abdullah/Downloads/nfstream-master/nfstream/engine/engine_cc.so': /home/abdullah/Downloads/nfstream-master/nfstream/engine/engine_cc.so: cannot open shared object file: No such file or directory.  Additionally, ctypes.util.find_library() did not manage to locate a library called '/home/abdullah/Downloads/nfstream-master/nfstream/engine/engine_cc.so'

**Comment by aouinizied** [comment]
How did you install NFStream?

Seems that you are using it from source without following buildings steps from the documentation.

Simplest way is to use
```python
 pip install nfstream
```

**Comment by drnpkr** [comment]
@01abdullah, the test will fail unless you build the project from the source. I presume that you are not going to develop/extend NFStream and that you want to use it. In such a case you do not need to run the tests.

Using the command above you will install the library. Then you have several options, for example:

- you can process a PCAP file and organize its packets into flows
- you can listen to packets live on your network interface
- develop your own NFPlugin and extend NFStream functionalities.

I strongly recommend you check these examples: https://github.com/nfstream/nfstream/tree/master/examples

Unless you want to fork NFStream and implement something in our way, you can forget about the tests.

**Comment by 01abdullah** [comment]
Hello Zied & Adrian,
Thank you so much for your efforts and support really appreciable.

I have already installed nfstream as below:
~$  pip install nfstream
Requirement already satisfied: nfstream in ./.local/lib/python3.8/site-packages (6.2.5)
Requirement already satisfied: dpkt>=1.9.4 in ./.local/lib/python3.8/site-packages (from nfstream) (1.9.5)
Requirement already satisfied: numpy<=1.18.5 in ./.local/lib/python3.8/site-packages (from nfstream) (1.18.5)
Requirement already satisfied: cffi>=1.14.0 in ./.local/lib/python3.8/site-packages (from nfstream) (1.14.5)
Requirement already satisfied: psutil>=5.7.0 in ./.local/lib/python3.8/site-packages (from nfstream) (5.8.0)
Requirement already satisfied: pandas>=1.0.3 in ./.local/lib/python3.8/site-packages (from nfstream) (1.2.3)
Requirement already satisfied: pycparser in ./.local/lib/python3.8/site-packages (from cffi>=1.14.0->nfstream) (2.20)
Requirement already satisfied: pytz>=2017.3 in /usr/lib/python3/dist-packages (from pandas>=1.0.3->nfstream) (2020.1)
Requirement already satisfied: python-dateutil>=2.7.3 in /usr/lib/python3/dist-packages (from pandas>=1.0.3->nfstream) (2.8.1)

--Also I have checked both examples mentioned:
CSV:
ImportError: cannot import name 'NFStreamer' from partially initialized module 'nfstream' (most likely due to a circular import) (/home/abdullah/Downloads/nfstream-master/nfstream/__init__.py)

I'm willing to use this project as primary module for my Master's degree thesis "Network traffic classification using neural networks (Bayesian Theorem)" supervised by Prof. Ayman Mohammad Bahaa-Eldin.
So I'm interested in NFPlugin to add machine learning algorithm to classify network traffic.

Any guidance  about the code or points of research or cooperation will be much appreciated. 

Thanks in advance.

**Comment by aouinizied** [comment]
You have some misconfiguration in your environnement because I see that your script is loading **/home/abdullah/Downloads/nfstream-master/nfstream/init.py** so mainly loading nfstream that you cloned and not the nfstream package installed using pip.

The simplest way is to use a virtual environement, the following steps must fix your issue.

```python
pip install virtualenv # INSTALL VIRTUALENV (1)
virtualenv venv-nfstream -p /usr/bin/python3.8 # CREATE YOUR VIRTUAL ENV (2)
source venv-nfstream/bin/activate # ACTIVATE YOUR VIRTUAL ENV (3)
pip install nfstream --upgrade # INSTALL NFSTREAM PACKAGE (4)
python flow_printer.py your_pcap_file.pcap # FOR PCAP PROCESSING (5)
sudo venv-nfstream/bin/python flow_printer.py your_interface_name  # FOR LIVE CAPTURE (6)
deactivate # DEACTIVATE YOUR VIRTUAL ENV WHEN YOU ARE DONE (7)
```

Note that steps (1) and (2) are done only once. If you deactivate your venv and you want it back just redo step (3).

Hope this helps.

Zied
