### ISSUE TITLE
Excessive memory usage

### ISSUE THREAD

**Issue by winterqz** [nfstream/nfstream#60]
**Describe the bug**
I use nfstream to monitor network interface,after longtime running,it used to much memory.

**To Reproduce**
the following is my params
```
my_streamer = NFStreamer(source="enp8s0",
                             decode_tunnels=True,
                             bpf_filter="(tcp or udp) and host not 192.168.30.24",
                             promiscuous_mode=True,
                             snapshot_length=1536,
                             idle_timeout=10,
                             active_timeout=1800,
                             accounting_mode=0,
                             n_dissections=20,
                             statistical_analysis=False,
                             splt_analysis=0,
                             n_meters=1,
                             performance_report=0,
                             udps=None)
```
I tried to change the params `idle_timeout` . However,the larger the number, the more memory is used. When i set `1`,the memory-usage won't increased.

**Expected behavior**
I know the meaning of this parameter.
When i set it to a large number, for example 10, how to release some memory?

**Screenshots**
![image](https://user-images.githubusercontent.com/49815962/112967278-b2b3cf00-917d-11eb-885d-51ed87e11717.png)

**Desktop (please complete the following information):**
 - OS: centos7
 - Python version 3.6
 - NFStream version 6.2.5

**Comment by aouinizied** [comment]
@winterqz can you activate performance_report=1 and share it with us to check the load you are processing?

**Comment by winterqz** [comment]
> @winterqz can you activate performance_report=1 and share it with us to check the load you are processing?

thanks, i will take your suggestion and show you the result.

**Comment by aouinizied** [comment]
@winterqz Any updates?

**Comment by winterqz** [comment]
I set `active_timeout=600` and show the usage of memory by the following picture
![JZ}U9M(D5AK1H7A KF3S$XC](https://user-images.githubusercontent.com/49815962/114571885-9483be00-9ca9-11eb-9319-650a38a0189a.png)
I think I got the result I wanted and your suggestion gave me some details about data flow,thanks again.
