### ISSUE TITLE
Multiple capture interface support

### ISSUE THREAD

**Issue by MatteoManzoni** [nfstream/nfstream#64]
**Describe the bug**
Trying to initialize multiple nfstreamer fails, making it impossible to capture traffic from multiple NICs

**To Reproduce**
1. Try to spawn multiple nfstream processes, on for each interface
2. One or more NFStreamer will crash

**Expected behavior**
Creating separated nfstream processes for each interface works correctly 

**Screenshots**
![Screen Shot 2021-05-13 at 12 50 27](https://user-images.githubusercontent.com/35832688/118121039-2427a400-b3f1-11eb-9d21-ab279ae22df2.png)
![Screen Shot 2021-05-13 at 12 50 59](https://user-images.githubusercontent.com/35832688/118121042-25f16780-b3f1-11eb-8871-77877de6621e.png)
![Screen Shot 2021-05-13 at 12 51 18](https://user-images.githubusercontent.com/35832688/118121044-25f16780-b3f1-11eb-809e-0916859dff6f.png)

**Desktop (please complete the following information):**
 - OS: Centos 7 / Debian Bullseye / Debian Buster
 - Python version: 3.9 / 3.7
 - NFStream version: 6.3.1

**Comment by aouinizied** [comment]
@MatteoManzoni Can you share a simple script that you use to spawn captures in order to reproduce?

**Comment by MatteoManzoni** [comment]
Hi @aouinizied, here's a snippet:
```python
def flowing_thread(interface, projects):
  try:
    re = redis.Redis(os.getenv('REDIS_HOST'), os.getenv('REDIS_PORT'))
    flow_iterator = NFStreamer(source=interface, statistical_analysis=True)
    for flow in flow_iterator:
      for k, v in generate(projects, flow):
        re.rpush(k, json.dumps(v))
  except BaseException as e:
    print('Thread for {} crashed: {}'.format(interface, str(e)))

def generate(projects, flow):
  for project in projects:
    name = project['name']
    for rule in project['rules']:
      condition = rule['condition']
      if eval(condition, {'flow': flow}):
        output_params = rule['output']
        output_dictionary = {k: flow.__getattribute__(v) for k,v in output_params.items()}
        yield '{}:{}'.format(name, rule['key']), output_dictionary

def main():
  with open('/config/rules.yml') as rule_file:
    rules = yaml.full_load(rule_file)
    workers = []

    for interface in interfaces:
      t = threading.Thread(target=flowing_thread, args=(interface, rules['projects']), daemon=True)
      workers.append(t)
      t.start()

    [t.join() for t in workers if t is not None and t.is_alive()]
```

All the dynamic rule matching is custom but the core and I think the problem is in the NFStreamer creation inside a thread (function `flowing_thread`)

Let me know if I can help in any other way,
Matteo

**Comment by MatteoManzoni** [comment]
Hi @aouinizied, have you been able to reproduce the problem?

**Comment by Lyonid** [comment]
Hi, I have the same issue in a similar environment. Any help or update would be appreciated.

**Comment by aouinizied** [comment]
@MatteoManzoni @Lyonid yes. When you start a streamer on Linux, kernel will be activated to load balance packets across several meters (child process of the streamer). I guess when using threading there is some conflicts that appears in your code. 
I will investigate it. The ideal would be to support multiple capture source in the API and hide this complexity to the final user.
A quick fix for your use case is to use multiprocessing instead of threading.
Will keep informed with updates.

**Comment by MatteoManzoni** [comment]
Thank you @aouinizied! I've already tried with multiprocessing but without any success. Even spawning 2 separate NFStream instance in 2 different container (Sharing the same kernel namespace, they are in the same kubernetes pod) causes the problem.

**Comment by aouinizied** [comment]
@MatteoManzoni @Lyonid Could you please upgrade to lastest version 6.3.2 and confirm if the issue is resolved. On my side, it is fixed.
