### ISSUE TITLE
`packet.transport_size` returns 64206 only

### ISSUE THREAD

**Issue by jeevan-thapa** [nfstream/nfstream#67]
**The transport_size attribute does not give the length of the transport layer but a constant value 64206**

**Code I ran**
```python
from nfstream import NFPlugin

class CustomPlugin(NFPlugin):
    def on_init(self, packet, flow):
        print(f"Raw Size: {packet.raw_size}, IP Size: {packet.ip_size}, Transport Size: {packet.transport_size}, Payload Size: {packet.payload_size}")

ml_streamer = NFStreamer(source="Gmail.pcap", udps=CustomPlugin(n=1), n_meters=1)

for flow in ml_streamer:
    print(flow)
    pass
```

**Output***
Raw Size: 1518, IP Size: 1500, Transport Size: 64206, Payload Size: 1448
Raw Size: 70, IP Size: 52, Transport Size: 64206, Payload Size: 0
Raw Size: 70, IP Size: 52, Transport Size: 64206, Payload Size: 0
Raw Size: 470, IP Size: 452, Transport Size: 64206, Payload Size: 400
Raw Size: 70, IP Size: 52, Transport Size: 64206, Payload Size: 0
Raw Size: 70, IP Size: 52, Transport Size: 64206, Payload Size: 0
Raw Size: 70, IP Size: 52, Transport Size: 64206, Payload Size: 0
Raw Size: 470, IP Size: 452, Transport Size: 64206, Payload Size: 400
Raw Size: 70, IP Size: 52, Transport Size: 64206, Payload Size: 0
Raw Size: 1284, IP Size: 1266, Transport Size: 64206, Payload Size: 1214
Raw Size: 70, IP Size: 52, Transport Size: 64206, Payload Size: 0
Raw Size: 70, IP Size: 52, Transport Size: 64206, Payload Size: 0
Raw Size: 70, IP Size: 52, Transport Size: 64206, Payload Size: 0
Raw Size: 1456, IP Size: 1438, Transport Size: 64206, Payload Size: 1386
Raw Size: 70, IP Size: 52, Transport Size: 64206, Payload Size: 0

**Expected behavior**
- Exact value of transport size

**Setup**
 - OS: - Ubuntu
 - Python version - 3.7
 - NFStream version - 6.3.3

**Comment by aouinizied** [comment]
Nice catch and I'm able to reproduce it. We will release a patch to fix this issue.

Thanks!

**Comment by aouinizied** [comment]
Fixed in this commit https://github.com/nfstream/nfstream/commit/ce14f506e447d865deb1e6afdd5c1148e2da464e
