### ISSUE TITLE
build files can not install for arm arch

### ISSUE THREAD

**Issue by SugiuraAyano** [nfstream/nfstream#68]
**Describe the bug**
Can't run the code as expected 

**To Reproduce**
1. create a python code which have from nfstream import something
2. See error

**Expected behavior**
Run Code

**Desktop (please complete the following information):**
 - OS: Debian 10 (Windows WSL2)
 - Python version: 3.9.6 
 - NFStream version: 6.3.3

**Additional context**
```py
from nfstream import NFStreamer

print("nfstream processing started. Use Ctrl+C to interrupt and save.")
total_flows = NFStreamer(source="eth0",
                         statistical_analysis=True,
                         splt_analysis=10,
                         performance_report=1).to_csv()
```

The code is same as csv_generator.py in examples

**Comment by SugiuraAyano** [comment]
same issue on Windows

**Comment by drnpkr** [comment]
Hi @SugiuraAyano,

That's weird since the code is running as expected in my test environment. Did you install properly nfstream through pip?

NFStream currently does not support Windows (see the documentation).

**Comment by SugiuraAyano** [comment]
Hello @drnpkr Thanks for your replying

I'm having two question right now 

First is, Windows subsystem Linux isn't work too?

Second is, 
I'm building nfstream in raspberry pi 3B (cause pip can't install the newest version only for 3.1.0)
and i ran the program it said no module name nfstream.
have ways to install my build nfstream?
sorry i'm new in programing

**Comment by SugiuraAyano** [comment]
I've been try the dist one but it said not supported
![image](https://user-images.githubusercontent.com/44806508/128819387-a4b659cc-1a9b-4d72-9756-bbb660456a7b.png)
![image](https://user-images.githubusercontent.com/44806508/128819394-0ccfade9-3eee-40cc-bb90-06a26f42eb7c.png)

**Comment by drnpkr** [comment]
I am confused. You run Windows on Pi 3? Probably not. The problem with your installation is that your architecture is not supported for installation using wheel.

You can install NFStream from source: https://www.nfstream.org/docs/

I have not tested Bash shell on Windows so I am not familiar how the subsystem is integrated into Windows and how are the dependencies satisfied. I would not expect that it will work this way.

**Comment by SugiuraAyano** [comment]
sorry for the confusion, I'm running raspberry pi os on Pi 3.

I'm already follow the doc and build from source but the whl file said it is not supported

**Comment by drnpkr** [comment]
Just to make sure I understand your problem correctly, did you follow the procedure from the beginning to the end?

So, you installed linux prerequisites, built dependencies from source (libgpg-error, libgcrypt, libpcap, and nDPI), and then, tried installing nfstream via pip?

**Comment by SugiuraAyano** [comment]
I follow the prerequisites, then build nfstream, then install build version via pip but fails

**Comment by SugiuraAyano** [comment]
Update: I reinstall the os and follow the instruction again, and i failed on nDPI build
![image](https://user-images.githubusercontent.com/44806508/130189406-9ef41a11-7767-4747-b771-909a8f50d98b.png)
seems need to add one more dependency json-c

**Comment by SugiuraAyano** [comment]
After some search i found why i can't install package.
You must edit the build filename, rename the manylinux_armv7l to linux_armv7l
Will close this issue now.

**Comment by SugiuraAyano** [comment]
reference: https://stackoverflow.com/questions/28107123/cannot-install-numpy-from-wheel-format?rq=1
