### ISSUE TITLE
ImportError: cannot import name NFStreamer from nfstream

### ISSUE THREAD

**Issue by SugiuraAyano** [nfstream/nfstream#71]
**Describe the bug**
can not import the module

**To Reproduce**
1. Use the csv_generator.py in example
2. Run the code
3. Error occur

**Expected behavior**
generates the csv file 

**Screenshots**
![image](https://user-images.githubusercontent.com/44806508/129316731-51684bf2-72f6-4b47-afbb-0dae476065a5.png)

**Desktop (please complete the following information):**
 - OS: Debian 10 (VM Windows Hosts)
 - Python version: 3.7.3
 - NFStream version 6.3.3

**Additional context**
I've install nfstream with pip, commands is 
python3 -m pip install nfstream
![image](https://user-images.githubusercontent.com/44806508/129317175-d27bf708-5e97-4d23-9326-c6d2a881a8e8.png)
vscode intellisence didn't show the module name either
![image](https://user-images.githubusercontent.com/44806508/129317358-13b0b9b4-1b54-4189-a0dd-3835f4cf408b.png)

**Comment by aouinizied** [comment]
@SugiuraAyano Can you please rename your script to another name than the module name (nfstream.py to nfstream_example.py) and retry?

**Comment by SugiuraAyano** [comment]
sorry i'm dumb this fix the problem.
will close this issue now.
