### ISSUE TITLE
Can't capture living traffic

### ISSUE THREAD

**Issue by stanpao** [nfstream/nfstream#73]
**Online capturing doesn't work.**
Local pcap parsing works but online capturing not.
No more clear traceback info.

**To Reproduce**
In [193]: streamer = NFStreamer('enp7s0')
In [194]: for i in streamer:
                  print(i)
`---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
~/miniconda3/envs/tensorflow/lib/python3.8/site-packages/nfstream/streamer.py in __iter__(self)
    334             if child_error is not None:
--> 335                 raise ValueError(child_error)
    336         except ValueError as observer_error:  # job initiation failed due to some bad observer parameters.

ValueError: Unable to activate source.

During handling of the above exception, another exception occurred:

ValueError                                Traceback (most recent call last)
<ipython-input-194-286d4d9e9aad> in <module>
----> 1 for i in streamer:
      2     print(i)
      3

~/miniconda3/envs/tensorflow/lib/python3.8/site-packages/nfstream/streamer.py in __iter__(self)
    335                 raise ValueError(child_error)
    336         except ValueError as observer_error:  # job initiation failed due to some bad observer parameters.
--> 337             raise ValueError(observer_error)
    338
    339     def to_csv(self, path=None, columns_to_anonymize=(), flows_per_file=0):

ValueError: Unable to activate source.

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Python version 3.8
 - NFStream version 6.3.4

**Comment by aouinizied** [comment]
@stanpao did you start it as root?

**Comment by stanpao** [comment]
embarrassed... u are right...
