### ISSUE TITLE
Build not complete dissector error

### ISSUE THREAD

**Issue by imagineTh4t** [nfstream/nfstream#86]
I try on Cent Os 8 machine. I did prerequirements. But i got this errors.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/local/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/nfstream/nfstream/meter.py", line 208, in meter_workflow
    dissector = setup_dissector(ffi, lib, n_dissections)
  File "/home/nfstream/nfstream/meter.py", line 139, in setup_dissector
    raise ValueError("Error while initializing dissector.")
ValueError: Error while initializing dissector.

**Comment by frkn4129** [comment]
@drnpkr 
when I looked at the last build, I realized that things were resolved.
is this true?

**Comment by aouinizied** [comment]
@frkn4129 Yes.
The dev branch of nfstream is sync with nDPI dev branch.
As nDPI is an active project, it happens that C structures definitions change (field addition, deletion etc.). As we bind this structure in python, this generate the error you observed.
So now it is fixed until the future change (example when this PR will be merged https://github.com/ntop/nDPI/pull/1354) .
Our future plans is to automate bindings generation to avoid such situation (https://github.com/ntop/nDPI/issues/1302).
A workaroud to you is to use the nDPI commit hash corresponding to last passed nfstream build when cloning nDPI.

Zied

**Comment by frkn4129** [comment]
@aouinizied thanks for answering. I have a one more question
nDPI made improvements in its latest update, this update how did it affect nfstream?

**Comment by aouinizied** [comment]
@frkn4129 as nDPI is faster as stated in this announce 
https://www.ntop.org/ndpi/introducing-ndpi-4-0-dpi-for-cybersecurity-and-traffic-analysis/
Consequently, nfstream dissection is faster.

**Comment by frkn4129** [comment]
thank you for taking your time. Zied :)
