### ISSUE TITLE
ETL files

### ISSUE THREAD

**Issue by 89z** [nfstream/nfstream#87]
Windows has two built in tools to capture packets, `pktmon` and `netsh trace`. However these tool produce ETL files instead of PCAP files.

It would be helpful if this program was able to read packets from ETL files.

**Comment by KSGJ-CLOUD** [comment]
I had installed nfstream packeage.But when  I use it，such as “from nfstream import NFStreamer”，backetground appears “cannot import name NFStreamer”，I don‘t know why？

**Comment by aouinizied** [comment]
@89z last released version add the suppirt of Windows Platform. Consequently, you can run nfstream in live mode. Is that ok for you as a temporary solution?

**Comment by 89z** [comment]
@aouinizied I am specifically trying to avoid installing any third party drivers, which Npcap would be. So thats not a good solution. If ETL is support that would be better, alternatively I am looking into solutions with proxy servers.
