### ISSUE TITLE
cannot import name NFStreamer

### ISSUE THREAD

**Issue by KSGJ-CLOUD** [nfstream/nfstream#89]
I had installed nfstream packeage.But when I use it，such as “from nfstream import NFStreamer”，backetground appears “cannot import name NFStreamer”，I don‘t know why？

**Comment by drnpkr** [comment]
I @KSGJ-CLOUD 

you have to be more specific regarding your problem.

You had installed NFStream using pip? Did you make sure that pip installed NFStream for the Python version you plan to use (I assume you know there might be pip and pip3 on your OS). Could you show us the output for:

pip -V
python -V
(alternatively python3 -V)

How do you import NFStream? Do you use a python program, e.g. the example that is provided here on GitHub (csv_generator.py).

**Comment by KSGJ-CLOUD** [comment]
Hello！
Thank your reply. I had resolved this problem, because I build new .py file name which conflicts NFStream.Now I rename this file，success！
Best，
Yin
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "nfstream/nfstream"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月15日(星期一) 下午4:07
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [nfstream/nfstream] cannot import name NFStreamer (Issue #89)





 
I @KSGJ-CLOUD
 
you have to be more specific regarding your problem.
 
You had installed NFStream using pip? Did you make sure that pip installed NFStream for the Python version you plan to use (I assume you know there might be pip and pip3 on your OS). Could you show us the output for:
 
pip -V
 python -V
 (alternatively python3 -V)
 
How do you import NFStream? Do you use a python program, e.g. the example that is provided here on GitHub (csv_generator.py).
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
