### ISSUE TITLE
Unable to activate source.

### ISSUE THREAD

**Issue by KSGJ-CLOUD** [nfstream/nfstream#90]
I write “my_streamer = NFStreamer(source='eno1')”my_streamer = NFStreamer(source='eno1')，point to ubuntu interfaces  name，but Background appears “ValueError: Unable to activate source.”ValueError: Unable to activate source.
Meanwhile，I am in win10 “my_streamer = NFStreamer(source=None)”.
Background appears Process finished with exit code 1.

**Comment by frkn4129** [comment]
@KSGJ-CLOUD did you run it as root

**Comment by KSGJ-CLOUD** [comment]
> @KSGJ-CLOUD did you run it as root

I am in anaconda environment

**Comment by KSGJ-CLOUD** [comment]
> @KSGJ-CLOUD did you run it as root or are you sure your ubuntu interface name is correct ?

interfaces name is correct. Beccause I Inquired
![image](https://user-images.githubusercontent.com/71766358/142574488-3609a6e9-0096-4f43-aab0-2d6b171ee38d.png)

**Comment by frkn4129** [comment]
i think i guess if you start it with root the problem will be solved

**Comment by KSGJ-CLOUD** [comment]
> i think i guess if you start it with root the problem will be solved

But if use root environment.  many python and tensorflow environment don‘t be used.

**Comment by KSGJ-CLOUD** [comment]
> i think i guess if you start it with root the problem will be solved

**Comment by aouinizied** [comment]
@KSGJ-CLOUD You must start as root for live capture.
In virtual env, you can still run as root and have packages from user defined env as follows:
```shell
sudo your_venv_name/bin/python your_script.py
```
