### ISSUE TITLE
Simply describe two bugs which have no obvious exception

### ISSUE THREAD

**Issue by stanpao** [nfstream/nfstream#91]
**Describe the bug**
Here I raise two bugs that have no obvious exception:
1. a few times flow key processing logic error happened:
Process ForkProcess-37:
Traceback (most recent call last):
  File "/home/baojunxian/miniconda3/envs/tensorflow/lib/python3.8/multiprocessing/process.py", line 313, in _bootstrap
    self.run()
  File "/home/baojunxian/miniconda3/envs/tensorflow/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/baojunxian/miniconda3/envs/tensorflow/lib/python3.8/site-packages/nfstream/meter.py", line 266, in meter_workflow
    meter_cleanup(cache, channel, udps, sync, n_dissections, statistics, splt, ffi, lib, dissector)
  File "/home/baojunxian/miniconda3/envs/tensorflow/lib/python3.8/site-packages/nfstream/meter.py", line 124, in meter_cleanup
    del cache[flow_key]
KeyError: (17, 0, 'Network', '218.4.4.4', 53, 41687, 0)

2. multiprocessing process are sometimes out of control and become zoombie process but no any explicit exception info raised, main get process hangs:
================================================
baojunx+ 2061796 3087338 15 15:17 pts/4    00:06:25 python main.py
baojunx+ 2069413 2061796  0 15:30 pts/4    00:00:15 [python] \<defunct>
baojunx+ 2069414 2061796  0 15:30 pts/4    00:00:14 [python] \<defunct>
baojunx+ 2069415 2061796  0 15:30 pts/4    00:00:15 [python] \<defunct>
baojunx+ 2069416 2061796  0 15:30 pts/4    00:00:14 [python] \<defunct>
baojunx+ 2069417 2061796  0 15:30 pts/4    00:00:15 [python] \<defunct>
baojunx+ 2069418 2061796  0 15:30 pts/4    00:00:15 [python] \<defunct>
baojunx+ 2069419 2061796  0 15:30 pts/4    00:00:15 [python] \<defunct>
================================================
I guess some exception raised but catched broadly  leading to some child pkt processing process exit to zoombie.

**To Reproduce**
Actually process the same batch of pcap, the occurance of error is random.

**Expected behavior**
1. explicit exception traceback info

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04 LTS
 - Python version 3.8
 - NFStream version 6.3.5

**Additional context**
I am trying to find the cause and report these implicit bugs here.

Another question:
From the source, if conversations between host A: port PA and host B: port PB and conversations between host A: port PB and host B: port PA will be processed as the same flow(for using the same seven elements tuple, although this scenario is very rare)?

**Comment by aouinizied** [comment]
@stanpao 
* from the log you are provinding I see that it's a modified version of NFStream and that the Flow Key do not match what is implemented in the mater. So Please, provide us with more information in order to be able to help you.
 * I guess your second point is related to previous point.
* Yes flow definition in NFStream is bidirectional and key is computed as you mentioneed. The scenario you mentionned should be rare but if you confirm that it is encoutered in your network, we can definitively move to a more strict key computation more strict.

**Comment by aouinizied** [comment]
@stanpao https://github.com/nfstream/nfstream/commit/6a1fd3307a03f7b8bb2882d97256ecbf948a89f7 address your last point.
