### ISSUE TITLE
How to pass SSLKEYLOG file?

### ISSUE THREAD

**Issue by vadimszzz** [nfstream/nfstream#92]
How to decrypt .pcap TLS traffic with .keylog file?

https://developer.mozilla.org/en-US/docs/Mozilla/Projects/NSS/Key_Log_Format

**Comment by aouinizied** [comment]
@vadimszzz We do not support such a feature in NFStream. Consequently, I will tag this issue as enhancement.
I do not ensure you that this will be implemented. Maybe we should start by implementing an NFPlugin to perform that.
What do you think?
