### ISSUE TITLE
how to obtain the data like UNSW-NB15

### ISSUE THREAD

**Issue by Chenhait** [nfstream/nfstream#95]
hi, I want to train a Intrusion Detection model with UNSW-NB15 dataset,
then do the real time Intrusion Detection  use the data collected by nfstream.
is it possible? 
I want to know if all feathers in UNSW-NB15 dataset can be collected with nfstream.
thank you so much if any advance or reference.
best wish

**Comment by stanpao** [comment]
Actually, nearly all statistical data can be collected by custom nfstream plugin. But I'm afraid that it's difficult to generate traffic features with the same statistical standard of UNSW-NB datasets. The exception may be ML sample shifting.

**Comment by aouinizied** [comment]
I didn't explore in details the specified dataset. I believe any flow feature is already within nfstream features or can be obtained by an NFPlugin. 
@stanpao what do you mean by same statistical standard of UNSW-NB dataset?

Zied

**Comment by stanpao** [comment]
> 

The standard way of collecting data feature. I think that may dataset are collect by some custom-made NTA tools or specific tools. It's may be difficult to obtain the same constructional features using nfstream by handwriting plugin like what other tools do. Different statistical method may cause prediction/validation dataset shift from training dataset . Dataset imbalance may be.
