### ISSUE TITLE
build failed 

### ISSUE THREAD

**Issue by frkn4129** [nfstream/nfstream#96]
Your linux build passing but my build was failed. How can i do ? 

----------------------------------------------------------------------
.Test accounting_mode parameter                                 : OK
.
----------------------------------------------------------------------
.Test active_timeout parameter                                  : OK
.
----------------------------------------------------------------------
E
----------------------------------------------------------------------
.Test bpf_filter parameter                                      : OK
.
----------------------------------------------------------------------
.Test decode_tunnels parameter                                  : OK
.
----------------------------------------------------------------------
E
----------------------------------------------------------------------
E
----------------------------------------------------------------------
E
----------------------------------------------------------------------
E
----------------------------------------------------------------------
.Test idle_timeout parameter                                    : OK
.
----------------------------------------------------------------------
E
----------------------------------------------------------------------
.Test n_dissections parameter                                   : OK
.
----------------------------------------------------------------------
.Test n_meters parameter                                        : OK
.
----------------------------------------------------------------------
.Test nDPI integration on 222 applications:
E
----------------------------------------------------------------------
.Test performance_report parameter                              : OK
.
----------------------------------------------------------------------
.Test promiscuous_mode parameter                                : OK
.
----------------------------------------------------------------------
.Test snapshot_length parameter                                 : OK
.
----------------------------------------------------------------------
.Test source parameter                                          : OK
.
----------------------------------------------------------------------
E
----------------------------------------------------------------------
.Test splt_analysis parameter                                   : OK
.
----------------------------------------------------------------------
E
----------------------------------------------------------------------
.Test statistical_analysis parameter                            : OK
.
----------------------------------------------------------------------
.Test system_visibility_extension_port parameter                : OK
.
----------------------------------------------------------------------
.Test system_visibility_mode parameter                          : OK
.
----------------------------------------------------------------------
.Test system_visibility_poll_ms parameter                       : OK
.
----------------------------------------------------------------------
E
----------------------------------------------------------------------
.Test udps parameter                                            : OK
.
======================================================================
ERROR: test_bpf (__main__.TestMethods)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/nfstream6.4.0/nfstream/nfstream/streamer.py", line 450, in __iter__
    raise ValueError(child_error)
ValueError: Error when loading engine library. This means that you are probably building nfstream from source and something went wrong during the engine compilation step. Please see: https://www.nfstream.org/docs/#building-nfstream-from-sourcesfor more information

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tests.py", line 365, in test_bpf
    for flow in streamer_test:
  File "/home/nfstream6.4.0/nfstream/nfstream/streamer.py", line 452, in __iter__
    raise ValueError(observer_error)
ValueError: Error when loading engine library. This means that you are probably building nfstream from source and something went wrong during the engine compilation step. Please see: https://www.nfstream.org/docs/#building-nfstream-from-sourcesfor more information

======================================================================
ERROR: test_dhcp (__main__.TestMethods)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/nfstream6.4.0/nfstream/nfstream/streamer.py", line 450, in __iter__
    raise ValueError(child_error)
ValueError: Error when loading engine library. This means that you are probably building nfstream from source and something went wrong during the engine compilation step. Please see: https://www.nfstream.org/docs/#building-nfstream-from-sourcesfor more information

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tests.py", line 414, in test_dhcp
    dhcp_df = NFStreamer(source=os.path.join("tests", "pcaps", "dhcp.pcap"),
  File "/home/nfstream6.4.0/nfstream/nfstream/streamer.py", line 491, in to_pandas
    total_flows = self.to_csv(path=temp_file_path, columns_to_anonymize=columns_to_anonymize, flows_per_file=0)
  File "/home/nfstream6.4.0/nfstream/nfstream/streamer.py", line 463, in to_csv
    for flow in self:
  File "/home/nfstream6.4.0/nfstream/nfstream/streamer.py", line 452, in __iter__
    raise ValueError(observer_error)
ValueError: Error when loading engine library. This means that you are probably building nfstream from source and something went wrong during the engine compilation step. Please see: https://www.nfstream.org/docs/#building-nfstream-from-sourcesfor more information

======================================================================
ERROR: test_expiration_management (__main__.TestMethods)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/nfstream6.4.0/nfstream/nfstream/streamer.py", line 450, in __iter__
    raise ValueError(child_error)
ValueError: Error when loading engine library. This means that you are probably building nfstream from source and something went wrong during the engine compilation step. Please see: https://www.nfstream.org/docs/#building-nfstream-from-sourcesfor more information

During handling of the above exception, another exception occurred:

**Comment by aouinizied** [comment]
Please clean your environment and retry making sure you follow the instructions  (reclone both nfstream and nDPI).
If the issue persist, the output of  python setup.py bdist_wheel step will be more helpful than the tests log.
